// Generated by scripts/generate.ts - do not edit
#ifndef QTS_OP_H
#define QTS_OP_H

typedef enum {
    QTS_OP_INVALID = 0, /** Invalid opcode - indicates uninitialized command */
    QTS_OP_SLOT_STORE = 1, /** Copy slot memory contents to a memory location owned by the caller */
    QTS_OP_SLOT_LOAD = 2, /** Copy data from a memory location into a slot */
    QTS_OP_SLOT_FREE = 3, /** Free a slot: for JSValueSlot, call JS_FreeValue to decrement refcount; for FuncListSlot, free the array of JSCFunctionListEntry */
    QTS_OP_NEW_OBJECT = 4, /** Create a new empty object (JS_NewObject) */
    QTS_OP_NEW_OBJECT_PROTO = 5, /** Create a new object with prototype (JS_NewObjectProto) */
    QTS_OP_NEW_ARRAY = 6, /** Create a new empty array (JS_NewArray) */
    QTS_OP_NEW_MAP = 7, /** Create a new empty Map (new Map()) */
    QTS_OP_NEW_SET = 8, /** Create a new empty Set (new Set()) */
    QTS_OP_NEW_DATE = 9, /** Create a Date object from timestamp (JS_NewDate) */
    QTS_OP_NEW_ERROR = 10, /** Create an Error object (JS_NewError or JS_New*Error) */
    QTS_OP_NEW_ARRAYBUFFER = 11, /** Create an ArrayBuffer by copying data (JS_NewArrayBufferCopy) */
    QTS_OP_NEW_TYPED_ARRAY = 12, /** Create a TypedArray view (JS_NewTypedArray) */
    QTS_OP_NEW_SYMBOL = 13, /** Create a Symbol (JS_NewSymbol or global symbol) */
    QTS_OP_NEW_FLOAT64 = 14, /** Create a float64 number value (JS_NewFloat64) */
    QTS_OP_NEW_STRING = 15, /** Create a string value (JS_NewStringLen) */
    QTS_OP_NEW_BIGINT = 16, /** Create a BigInt value from i64 (JS_NewBigInt64) */
    QTS_OP_NEW_FUNC = 17, /** Create a host function (QTS_NewFunction) */
    QTS_OP_SET_STR_VALUE = 18, /** Set property by string key to JSValue from slot (JS_SetPropertyStr) */
    QTS_OP_SET_STR_NULL = 19, /** Set property by string key to null */
    QTS_OP_SET_STR_UNDEF = 20, /** Set property by string key to undefined */
    QTS_OP_SET_STR_BOOL = 21, /** Set property by string key to boolean */
    QTS_OP_SET_STR_INT32 = 22, /** Set property by string key to int32 */
    QTS_OP_SET_STR_F64 = 23, /** Set property by string key to float64 */
    QTS_OP_SET_STR_BIGINT = 24, /** Set property by string key to BigInt */
    QTS_OP_SET_STR_STRING = 25, /** Set property by string key to string value */
    QTS_OP_SET_IDX_VALUE = 26, /** Set array element by index to JSValue from slot (JS_SetPropertyUint32) */
    QTS_OP_SET_IDX_NULL = 27, /** Set array element by index to null */
    QTS_OP_SET_IDX_UNDEF = 28, /** Set array element by index to undefined */
    QTS_OP_SET_IDX_BOOL = 29, /** Set array element by index to boolean */
    QTS_OP_SET_IDX_INT32 = 30, /** Set array element by index to int32 */
    QTS_OP_SET_IDX_F64 = 31, /** Set array element by index to float64 */
    QTS_OP_SET_IDX_BIGINT = 32, /** Set array element by index to BigInt */
    QTS_OP_SET_IDX_STRING = 33, /** Set array element by index to string */
    QTS_OP_SET_VALUE_VALUE = 34, /** Set property using JSValue key (JS_SetProperty) */
    QTS_OP_DEF_VALUE_GETSET = 35, /** define a getter/setter property on object */
    QTS_OP_GET_VALUE = 36, /** Get property using JSValue key (JS_GetProperty) */
    QTS_OP_GET_STR = 37, /** Get property by string key (JS_GetPropertyStr) */
    QTS_OP_GET_IDX = 38, /** Get property by numeric index (JS_GetPropertyUint32) */
    QTS_OP_GLOBAL = 39, /** Get the global object (JS_GetGlobalObject) */
    QTS_OP_GLOBAL_GET_STR = 40, /** Get property by string key from global object (JS_GetPropertyStr) */
    QTS_OP_GLOBAL_SET_STR = 41, /** Set property by string key on global object (JS_SetPropertyStr) */
    QTS_OP_MAP_SET = 42, /** Call map.set(key, value) using JSValue key */
    QTS_OP_MAP_SET_STR = 43, /** Call map.set(key, value) with string key */
    QTS_OP_SET_ADD = 44, /** Call set.add(value) */
    QTS_OP_CALL = 45, /** Call a function (JS_Call) eg `func(args)` with up to 10 arguments in slots */
    QTS_OP_CALL_ARGV = 46, /** Call a function with any number of arguments stored in adjacent memory (JS_Call) */
    QTS_OP_EVAL = 47, /** Evaluate JavaScript code (JS_Eval) */
    QTS_OP_THROW = 48, /** Throw an exception (JS_Throw) */
    QTS_OP_RESOLVE_EXC = 49, /** Resolve exception - if maybe_exc is exception, return the exception value */
    QTS_OP_BYTECODE_WRITE = 50, /** Serialize a value to binary (JS_WriteObject) */
    QTS_OP_BYTECODE_READ = 51, /** Deserialize a value from binary (JS_ReadObject) */
    QTS_OP_FUNCLIST_NEW = 52, /** Allocate a new JSCFunctionListEntry array */
    QTS_OP_FUNCLIST_ASSIGN = 53, /** Assign all properties defined in the funclist to the target object (JS_SetPropertyFunctionList) */
    QTS_OP_FUNCLIST_DEF_CFUNC = 54, /** Set funclist entry to JS_DEF_CFUNC */
    QTS_OP_FUNCLIST_DEF_CFUNC_CTOR = 55, /** Set funclist entry to JS_DEF_CFUNC with constructor proto */
    QTS_OP_FUNCLIST_DEF_CGETSET = 56, /** Set funclist entry to JS_DEF_CGETSET */
    QTS_OP_FUNCLIST_DEF_STRING = 57, /** Set funclist entry to JS_DEF_PROP_STRING */
    QTS_OP_FUNCLIST_DEF_INT32 = 58, /** Set funclist entry to JS_DEF_PROP_INT32 */
    QTS_OP_FUNCLIST_DEF_INT64 = 59, /** Set funclist entry to JS_DEF_PROP_INT64 (index in slot_c) */
    QTS_OP_FUNCLIST_DEF_DOUBLE = 60, /** Set funclist entry to JS_DEF_PROP_DOUBLE (index in slot_c) */
    QTS_OP_FUNCLIST_DEF_NULL = 61, /** Set funclist entry to JS_DEF_PROP_NULL */
    QTS_OP_FUNCLIST_DEF_UNDEFINED = 62, /** Set funclist entry to JS_DEF_PROP_UNDEFINED */
    QTS_OP_FUNCLIST_DEF_OBJECT = 63, /** Set funclist entry to JS_DEF_OBJECT (nested object with its own funclist) */
} QTS_Opcode;

#endif // QTS_OP_H
