// Generated by scripts/generate.ts - do not edit
#ifndef QTS_OP_H
#define QTS_OP_H

typedef enum {
    QTS_OP_INVALID = 0, /** Invalid opcode - indicates uninitialized command */
    QTS_OP_NEW_OBJECT = 1, /** Create a new empty object (JS_NewObject) */
    QTS_OP_NEW_OBJECT_PROTO = 2, /** Create a new object with prototype (JS_NewObjectProto) */
    QTS_OP_NEW_ARRAY = 3, /** Create a new empty array (JS_NewArray) */
    QTS_OP_NEW_DATE = 4, /** Create a Date object from timestamp (JS_NewDate) */
    QTS_OP_NEW_ERROR = 5, /** Create an Error object (JS_NewError or JS_New*Error) */
    QTS_OP_NEW_ARRAYBUFFER = 6, /** Create an ArrayBuffer by copying data (JS_NewArrayBufferCopy) */
    QTS_OP_NEW_TYPED_ARRAY = 7, /** Create a TypedArray view (JS_NewTypedArray) */
    QTS_OP_NEW_SYMBOL = 8, /** Create a Symbol (JS_NewSymbol or global symbol) */
    QTS_OP_NEW_FLOAT64 = 9, /** Create a float64 number value (JS_NewFloat64) */
    QTS_OP_NEW_STRING = 10, /** Create a string value (JS_NewStringLen) */
    QTS_OP_NEW_BIGINT = 11, /** Create a BigInt value from i64 (JS_NewBigInt64) */
    QTS_OP_NEW_FUNC = 12, /** Create a host function (QTS_NewFunction) */
    QTS_OP_SET_STR_VALUE = 13, /** Set property by string key to JSValue from slot (JS_SetPropertyStr) */
    QTS_OP_SET_STR_NULL = 14, /** Set property by string key to null */
    QTS_OP_SET_STR_UNDEF = 15, /** Set property by string key to undefined */
    QTS_OP_SET_STR_BOOL = 16, /** Set property by string key to boolean */
    QTS_OP_SET_STR_INT32 = 17, /** Set property by string key to int32 */
    QTS_OP_SET_STR_F64 = 18, /** Set property by string key to float64 */
    QTS_OP_SET_STR_BIGINT = 19, /** Set property by string key to BigInt */
    QTS_OP_SET_STR_STRING = 20, /** Set property by string key to string value */
    QTS_OP_SET_IDX_VALUE = 21, /** Set array element by index to JSValue from slot (JS_SetPropertyUint32) */
    QTS_OP_SET_IDX_NULL = 22, /** Set array element by index to null */
    QTS_OP_SET_IDX_UNDEF = 23, /** Set array element by index to undefined */
    QTS_OP_SET_IDX_BOOL = 24, /** Set array element by index to boolean */
    QTS_OP_SET_IDX_INT32 = 25, /** Set array element by index to int32 */
    QTS_OP_SET_IDX_F64 = 26, /** Set array element by index to float64 */
    QTS_OP_SET_IDX_BIGINT = 27, /** Set array element by index to BigInt */
    QTS_OP_SET_IDX_STRING = 28, /** Set array element by index to string */
    QTS_OP_SET = 29, /** Set property using JSValue key (JS_SetProperty) */
    QTS_OP_DEF_GETSET = 30, /** define a getter/setter property on object */
    QTS_OP_GET = 31, /** Get property using JSValue key (JS_GetProperty) */
    QTS_OP_GET_STR = 32, /** Get property by string key (JS_GetPropertyStr) */
    QTS_OP_GET_IDX = 33, /** Get property by numeric index (JS_GetPropertyUint32) */
    QTS_OP_GLOBAL = 34, /** Get the global object (JS_GetGlobalObject) */
    QTS_OP_GLOBAL_GET_STR = 35, /** Get property by string key from global object (JS_GetPropertyStr) */
    QTS_OP_GLOBAL_SET_STR = 36, /** Set property by string key on global object (JS_SetPropertyStr) */
    QTS_OP_MAP_SET = 37, /** Call map.set(key, value) using JSValue key */
    QTS_OP_MAP_SET_STR = 38, /** Call map.set(key, value) with string key */
    QTS_OP_SET_ADD = 39, /** Call set.add(value) */
    QTS_OP_CALL = 40, /** Call a function (JS_Call) eg `func(args)` */
    QTS_OP_CALL_CTOR = 41, /** Call a constructor (JS_CallConstructor) eg `new Ctor(args)` */
    QTS_OP_EVAL = 42, /** Evaluate JavaScript code (JS_Eval) */
    QTS_OP_THROW = 43, /** Throw an exception (JS_Throw) */
    QTS_OP_RESOLVE_EXC = 44, /** Resolve exception - if maybe_exc is exception, return the exception value */
    QTS_OP_DUP = 45, /** Duplicate a value (JS_DupValue) - increment refcount */
    QTS_OP_DUP_PTR = 46, /** Duplicate a JSValue* pointer into a JSValueSlot */
    QTS_OP_FREE = 47, /** Free a value (JS_FreeValue) - decrement refcount */
    QTS_OP_FREE_PTR = 48, /** Free a JSValue* pointer - JS_FreeValue the value, then free the pointer */
    QTS_OP_BYTECODE_WRITE = 49, /** Serialize a value to binary (JS_WriteObject) */
    QTS_OP_BYTECODE_READ = 50, /** Deserialize a value from binary (JS_ReadObject) */
    QTS_OP_FUNCLIST_NEW = 51, /** Allocate a new JSCFunctionListEntry array */
    QTS_OP_FUNCLIST_ASSIGN = 52, /** Assign all properties defined in the funclist to the target object (JS_SetPropertyFunctionList) */
    QTS_OP_FUNCLIST_FREE = 53, /** Free a funclist array */
    QTS_OP_FUNCLIST_DEF_CFUNC = 54, /** Set funclist entry to JS_DEF_CFUNC */
    QTS_OP_FUNCLIST_DEF_CFUNC_CTOR = 55, /** Set funclist entry to JS_DEF_CFUNC with constructor proto */
    QTS_OP_FUNCLIST_DEF_CGETSET = 56, /** Set funclist entry to JS_DEF_CGETSET */
    QTS_OP_FUNCLIST_DEF_STRING = 57, /** Set funclist entry to JS_DEF_PROP_STRING */
    QTS_OP_FUNCLIST_DEF_INT32 = 58, /** Set funclist entry to JS_DEF_PROP_INT32 */
    QTS_OP_FUNCLIST_DEF_INT64 = 59, /** Set funclist entry to JS_DEF_PROP_INT64 (index in slot_c) */
    QTS_OP_FUNCLIST_DEF_DOUBLE = 60, /** Set funclist entry to JS_DEF_PROP_DOUBLE (index in slot_c) */
    QTS_OP_FUNCLIST_DEF_NULL = 61, /** Set funclist entry to JS_DEF_PROP_NULL */
    QTS_OP_FUNCLIST_DEF_UNDEFINED = 62, /** Set funclist entry to JS_DEF_PROP_UNDEFINED */
    QTS_OP_FUNCLIST_DEF_OBJECT = 63, /** Set funclist entry to JS_DEF_OBJECT (nested object with its own funclist) */
} QTS_Opcode;

#endif // QTS_OP_H
