// This file is generated by scripts/generate.ts ops - do not edit manually

import type {
  BorrowedHeapCharPointer,
  CommandPtr,
  EvalFlags,
  Float64,
  FuncListSlot,
  HostRefId,
  Int32,
  Int64,
  JSCFunctionTypePointer,
  JSPropFlags,
  JSValuePointer,
  JSValueSlot,
  NewErrorFlags,
  NewTypedArrayFlags,
  SetPropFlags,
  Uint32,
  Uint8,
} from "@jitl/quickjs-ffi-types"
import type { AnyRef, FuncListRef, JSValueRef } from "./command-types"

export const INVALID = 0 as const
export const NEW_OBJECT = 1 as const
export const NEW_OBJECT_PROTO = 2 as const
export const NEW_ARRAY = 3 as const
export const NEW_MAP = 4 as const
export const NEW_SET = 5 as const
export const NEW_DATE = 6 as const
export const NEW_ERROR = 7 as const
export const NEW_ARRAYBUFFER = 8 as const
export const NEW_TYPED_ARRAY = 9 as const
export const NEW_SYMBOL = 10 as const
export const NEW_FLOAT64 = 11 as const
export const NEW_STRING = 12 as const
export const NEW_BIGINT = 13 as const
export const NEW_FUNC = 14 as const
export const SET_STR_VALUE = 15 as const
export const SET_STR_NULL = 16 as const
export const SET_STR_UNDEF = 17 as const
export const SET_STR_BOOL = 18 as const
export const SET_STR_INT32 = 19 as const
export const SET_STR_F64 = 20 as const
export const SET_STR_BIGINT = 21 as const
export const SET_STR_STRING = 22 as const
export const SET_IDX_VALUE = 23 as const
export const SET_IDX_NULL = 24 as const
export const SET_IDX_UNDEF = 25 as const
export const SET_IDX_BOOL = 26 as const
export const SET_IDX_INT32 = 27 as const
export const SET_IDX_F64 = 28 as const
export const SET_IDX_BIGINT = 29 as const
export const SET_IDX_STRING = 30 as const
export const SET = 31 as const
export const DEF_GETSET = 32 as const
export const GET = 33 as const
export const GET_STR = 34 as const
export const GET_IDX = 35 as const
export const GLOBAL = 36 as const
export const GLOBAL_GET_STR = 37 as const
export const GLOBAL_SET_STR = 38 as const
export const MAP_SET = 39 as const
export const MAP_SET_STR = 40 as const
export const SET_ADD = 41 as const
export const CALL = 42 as const
export const CALL_CTOR = 43 as const
export const EVAL = 44 as const
export const THROW = 45 as const
export const RESOLVE_EXC = 46 as const
export const DUP = 47 as const
export const DUP_PTR = 48 as const
export const FREE = 49 as const
export const FREE_PTR = 50 as const
export const BYTECODE_WRITE = 51 as const
export const BYTECODE_READ = 52 as const
export const FUNCLIST_NEW = 53 as const
export const FUNCLIST_ASSIGN = 54 as const
export const FUNCLIST_FREE = 55 as const
export const FUNCLIST_DEF_CFUNC = 56 as const
export const FUNCLIST_DEF_CFUNC_CTOR = 57 as const
export const FUNCLIST_DEF_CGETSET = 58 as const
export const FUNCLIST_DEF_STRING = 59 as const
export const FUNCLIST_DEF_INT32 = 60 as const
export const FUNCLIST_DEF_INT64 = 61 as const
export const FUNCLIST_DEF_DOUBLE = 62 as const
export const FUNCLIST_DEF_NULL = 63 as const
export const FUNCLIST_DEF_UNDEFINED = 64 as const
export const FUNCLIST_DEF_OBJECT = 65 as const

interface BaseCommand {
  kind: number
  barrier?: boolean
  label?: string
}

export interface InvalidCommand extends BaseCommand {
  kind: typeof INVALID
}

export interface NewObjectCommand extends BaseCommand {
  kind: typeof NEW_OBJECT
  resultSlot: JSValueRef
}

export interface NewObjectProtoCommand extends BaseCommand {
  kind: typeof NEW_OBJECT_PROTO
  resultSlot: JSValueRef
  protoSlot: JSValueRef
}

export interface NewArrayCommand extends BaseCommand {
  kind: typeof NEW_ARRAY
  resultSlot: JSValueRef
}

export interface NewMapCommand extends BaseCommand {
  kind: typeof NEW_MAP
  resultSlot: JSValueRef
}

export interface NewSetCommand extends BaseCommand {
  kind: typeof NEW_SET
  resultSlot: JSValueRef
}

export interface NewDateCommand extends BaseCommand {
  kind: typeof NEW_DATE
  resultSlot: JSValueRef
  timestamp: number
}

export interface NewErrorCommand extends BaseCommand {
  kind: typeof NEW_ERROR
  resultSlot: JSValueRef
  newErrorFlags: NewErrorFlags
  message: string
  name: string
}

export interface NewArraybufferCommand extends BaseCommand {
  kind: typeof NEW_ARRAYBUFFER
  resultSlot: JSValueRef
  dataBytes: Uint8Array
}

export interface NewTypedArrayCommand extends BaseCommand {
  kind: typeof NEW_TYPED_ARRAY
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  arrayType: NewTypedArrayFlags
  sourceOffset: number
  length: number
}

export interface NewSymbolCommand extends BaseCommand {
  kind: typeof NEW_SYMBOL
  resultSlot: JSValueRef
  isGlobal: number
  desc: string
}

export interface NewFloat64Command extends BaseCommand {
  kind: typeof NEW_FLOAT64
  resultSlot: JSValueRef
  value: number
}

export interface NewStringCommand extends BaseCommand {
  kind: typeof NEW_STRING
  resultSlot: JSValueRef
  str: string
}

export interface NewBigintCommand extends BaseCommand {
  kind: typeof NEW_BIGINT
  resultSlot: JSValueRef
  value: bigint
}

export interface NewFuncCommand extends BaseCommand {
  kind: typeof NEW_FUNC
  resultSlot: JSValueRef
  arity: number
  isConstructor: number
  name: string
  hostRefId: HostRefId
}

export interface SetStrValueCommand extends BaseCommand {
  kind: typeof SET_STR_VALUE
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrNullCommand extends BaseCommand {
  kind: typeof SET_STR_NULL
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrUndefCommand extends BaseCommand {
  kind: typeof SET_STR_UNDEF
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrBoolCommand extends BaseCommand {
  kind: typeof SET_STR_BOOL
  targetSlot: JSValueRef
  boolVal: number
  flags: SetPropFlags
  key: string
}

export interface SetStrInt32Command extends BaseCommand {
  kind: typeof SET_STR_INT32
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
  intVal: number
}

export interface SetStrF64Command extends BaseCommand {
  kind: typeof SET_STR_F64
  targetSlot: JSValueRef
  flags: SetPropFlags
  f64Val: number
  key: string
}

export interface SetStrBigintCommand extends BaseCommand {
  kind: typeof SET_STR_BIGINT
  targetSlot: JSValueRef
  flags: SetPropFlags
  i64Val: bigint
  key: string
}

export interface SetStrStringCommand extends BaseCommand {
  kind: typeof SET_STR_STRING
  targetSlot: JSValueRef
  flags: SetPropFlags
  str: string
  key: string
}

export interface SetIdxValueCommand extends BaseCommand {
  kind: typeof SET_IDX_VALUE
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
  index: number
}

export interface SetIdxNullCommand extends BaseCommand {
  kind: typeof SET_IDX_NULL
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: number
}

export interface SetIdxUndefCommand extends BaseCommand {
  kind: typeof SET_IDX_UNDEF
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: number
}

export interface SetIdxBoolCommand extends BaseCommand {
  kind: typeof SET_IDX_BOOL
  targetSlot: JSValueRef
  boolVal: number
  flags: SetPropFlags
  index: number
}

export interface SetIdxInt32Command extends BaseCommand {
  kind: typeof SET_IDX_INT32
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: number
  intVal: number
}

export interface SetIdxF64Command extends BaseCommand {
  kind: typeof SET_IDX_F64
  targetSlot: JSValueRef
  flags: SetPropFlags
  f64Val: number
  index: number
}

export interface SetIdxBigintCommand extends BaseCommand {
  kind: typeof SET_IDX_BIGINT
  targetSlot: JSValueRef
  flags: SetPropFlags
  i64Val: bigint
  index: number
}

export interface SetIdxStringCommand extends BaseCommand {
  kind: typeof SET_IDX_STRING
  targetSlot: JSValueRef
  flags: SetPropFlags
  str: string
  index: number
}

export interface SetCommand extends BaseCommand {
  kind: typeof SET
  targetSlot: JSValueRef
  keySlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
}

export interface DefGetsetCommand extends BaseCommand {
  kind: typeof DEF_GETSET
  targetSlot: JSValueRef
  flags: JSPropFlags
  getterRef: HostRefId
  setterRef: HostRefId
  key: string
}

export interface GetCommand extends BaseCommand {
  kind: typeof GET
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  keySlot: JSValueRef
}

export interface GetStrCommand extends BaseCommand {
  kind: typeof GET_STR
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  key: string
}

export interface GetIdxCommand extends BaseCommand {
  kind: typeof GET_IDX
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  index: number
}

export interface GlobalCommand extends BaseCommand {
  kind: typeof GLOBAL
  resultSlot: JSValueRef
}

export interface GlobalGetStrCommand extends BaseCommand {
  kind: typeof GLOBAL_GET_STR
  resultSlot: JSValueRef
  key: string
}

export interface GlobalSetStrCommand extends BaseCommand {
  kind: typeof GLOBAL_SET_STR
  valueSlot: JSValueRef
  flags: JSPropFlags
  key: string
}

export interface MapSetCommand extends BaseCommand {
  kind: typeof MAP_SET
  targetSlot: JSValueRef
  keySlot: JSValueRef
  valueSlot: JSValueRef
}

export interface MapSetStrCommand extends BaseCommand {
  kind: typeof MAP_SET_STR
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  key: string
}

export interface SetAddCommand extends BaseCommand {
  kind: typeof SET_ADD
  targetSlot: JSValueRef
  valueSlot: JSValueRef
}

export interface CallCommand extends BaseCommand {
  kind: typeof CALL
  barrier: true
  resultSlot: JSValueRef
  funcSlot: JSValueRef
  thisSlot: JSValueRef
  argv: readonly JSValueRef[]
}

export interface CallCtorCommand extends BaseCommand {
  kind: typeof CALL_CTOR
  barrier: true
  resultSlot: JSValueRef
  ctorSlot: JSValueRef
  argv: readonly JSValueRef[]
}

export interface EvalCommand extends BaseCommand {
  kind: typeof EVAL
  barrier: true
  resultSlot: JSValueRef
  callFlags: EvalFlags
  code: string
  filename: string
}

export interface ThrowCommand extends BaseCommand {
  kind: typeof THROW
  errorSlot: JSValueRef
}

export interface ResolveExcCommand extends BaseCommand {
  kind: typeof RESOLVE_EXC
  resultSlot: JSValueRef
  maybeExcSlot: JSValueRef
}

export interface DupCommand extends BaseCommand {
  kind: typeof DUP
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
}

export interface DupPtrCommand extends BaseCommand {
  kind: typeof DUP_PTR
  resultSlot: JSValueRef
  valuePtr: JSValueRef
}

export interface FreeCommand extends BaseCommand {
  kind: typeof FREE
  targetSlot: JSValueRef
}

export interface FreePtrCommand extends BaseCommand {
  kind: typeof FREE_PTR
  valuePtr: JSValueRef
}

export interface BytecodeWriteCommand extends BaseCommand {
  kind: typeof BYTECODE_WRITE
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  flags: number
}

export interface BytecodeReadCommand extends BaseCommand {
  kind: typeof BYTECODE_READ
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  flags: number
}

export interface FunclistNewCommand extends BaseCommand {
  kind: typeof FUNCLIST_NEW
  resultFunclistSlot: FuncListRef
  count: number
}

export interface FunclistAssignCommand extends BaseCommand {
  kind: typeof FUNCLIST_ASSIGN
  targetSlot: JSValueRef
  sourceFunclistSlot: FuncListRef
}

export interface FunclistFreeCommand extends BaseCommand {
  kind: typeof FUNCLIST_FREE
  targetFunclistSlot: FuncListRef
}

export interface FunclistDefCfuncCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_CFUNC
  targetFunclistSlot: FuncListRef
  arity: number
  flags: JSPropFlags
  index: number
  funcName: string
  cFuncPtr: JSCFunctionTypePointer
}

export interface FunclistDefCfuncCtorCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_CFUNC_CTOR
  targetFunclistSlot: FuncListRef
  arity: number
  flags: JSPropFlags
  index: number
  funcName: string
  cFuncPtr: JSCFunctionTypePointer
}

export interface FunclistDefCgetsetCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_CGETSET
  targetFunclistSlot: FuncListRef
  index: number
  flags: JSPropFlags
  key: string
  getterPtr: JSCFunctionTypePointer
  setterPtr: JSCFunctionTypePointer
}

export interface FunclistDefStringCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_STRING
  targetFunclistSlot: FuncListRef
  index: number
  flags: JSPropFlags
  str: string
  name: string
}

export interface FunclistDefInt32Command extends BaseCommand {
  kind: typeof FUNCLIST_DEF_INT32
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  index: number
  intVal: number
  key: string
}

export interface FunclistDefInt64Command extends BaseCommand {
  kind: typeof FUNCLIST_DEF_INT64
  targetFunclistSlot: FuncListRef
  index: number
  flags: JSPropFlags
  i64Val: bigint
  name: string
}

export interface FunclistDefDoubleCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_DOUBLE
  targetFunclistSlot: FuncListRef
  index: number
  flags: JSPropFlags
  f64Val: number
  key: string
}

export interface FunclistDefNullCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_NULL
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: number
}

export interface FunclistDefUndefinedCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_UNDEFINED
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: number
}

export interface FunclistDefObjectCommand extends BaseCommand {
  kind: typeof FUNCLIST_DEF_OBJECT
  targetFunclistSlot: FuncListRef
  objectFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: number
}

export type Command = InvalidCommand |
  NewObjectCommand |
  NewObjectProtoCommand |
  NewArrayCommand |
  NewMapCommand |
  NewSetCommand |
  NewDateCommand |
  NewErrorCommand |
  NewArraybufferCommand |
  NewTypedArrayCommand |
  NewSymbolCommand |
  NewFloat64Command |
  NewStringCommand |
  NewBigintCommand |
  NewFuncCommand |
  SetStrValueCommand |
  SetStrNullCommand |
  SetStrUndefCommand |
  SetStrBoolCommand |
  SetStrInt32Command |
  SetStrF64Command |
  SetStrBigintCommand |
  SetStrStringCommand |
  SetIdxValueCommand |
  SetIdxNullCommand |
  SetIdxUndefCommand |
  SetIdxBoolCommand |
  SetIdxInt32Command |
  SetIdxF64Command |
  SetIdxBigintCommand |
  SetIdxStringCommand |
  SetCommand |
  DefGetsetCommand |
  GetCommand |
  GetStrCommand |
  GetIdxCommand |
  GlobalCommand |
  GlobalGetStrCommand |
  GlobalSetStrCommand |
  MapSetCommand |
  MapSetStrCommand |
  SetAddCommand |
  CallCommand |
  CallCtorCommand |
  EvalCommand |
  ThrowCommand |
  ResolveExcCommand |
  DupCommand |
  DupPtrCommand |
  FreeCommand |
  FreePtrCommand |
  BytecodeWriteCommand |
  BytecodeReadCommand |
  FunclistNewCommand |
  FunclistAssignCommand |
  FunclistFreeCommand |
  FunclistDefCfuncCommand |
  FunclistDefCfuncCtorCommand |
  FunclistDefCgetsetCommand |
  FunclistDefStringCommand |
  FunclistDefInt32Command |
  FunclistDefInt64Command |
  FunclistDefDoubleCommand |
  FunclistDefNullCommand |
  FunclistDefUndefinedCommand |
  FunclistDefObjectCommand

export function InvalidCmd(): InvalidCommand {
  return {
    kind: INVALID,
  }
}

export function NewObjectCmd(resultSlot: JSValueRef): NewObjectCommand {
  return {
    kind: NEW_OBJECT,
    resultSlot,
  }
}

export function NewObjectProtoCmd(resultSlot: JSValueRef, protoSlot: JSValueRef): NewObjectProtoCommand {
  return {
    kind: NEW_OBJECT_PROTO,
    resultSlot,
    protoSlot,
  }
}

export function NewArrayCmd(resultSlot: JSValueRef): NewArrayCommand {
  return {
    kind: NEW_ARRAY,
    resultSlot,
  }
}

export function NewMapCmd(resultSlot: JSValueRef): NewMapCommand {
  return {
    kind: NEW_MAP,
    resultSlot,
  }
}

export function NewSetCmd(resultSlot: JSValueRef): NewSetCommand {
  return {
    kind: NEW_SET,
    resultSlot,
  }
}

export function NewDateCmd(resultSlot: JSValueRef, timestamp: number): NewDateCommand {
  return {
    kind: NEW_DATE,
    resultSlot,
    timestamp,
  }
}

export function NewErrorCmd(resultSlot: JSValueRef, newErrorFlags: NewErrorFlags, message: string, name: string): NewErrorCommand {
  return {
    kind: NEW_ERROR,
    resultSlot,
    newErrorFlags,
    message,
    name,
  }
}

export function NewArraybufferCmd(resultSlot: JSValueRef, dataBytes: Uint8Array): NewArraybufferCommand {
  return {
    kind: NEW_ARRAYBUFFER,
    resultSlot,
    dataBytes,
  }
}

export function NewTypedArrayCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, arrayType: NewTypedArrayFlags, sourceOffset: number, length: number): NewTypedArrayCommand {
  return {
    kind: NEW_TYPED_ARRAY,
    resultSlot,
    sourceSlot,
    arrayType,
    sourceOffset,
    length,
  }
}

export function NewSymbolCmd(resultSlot: JSValueRef, isGlobal: number, desc: string): NewSymbolCommand {
  return {
    kind: NEW_SYMBOL,
    resultSlot,
    isGlobal,
    desc,
  }
}

export function NewFloat64Cmd(resultSlot: JSValueRef, value: number): NewFloat64Command {
  return {
    kind: NEW_FLOAT64,
    resultSlot,
    value,
  }
}

export function NewStringCmd(resultSlot: JSValueRef, str: string): NewStringCommand {
  return {
    kind: NEW_STRING,
    resultSlot,
    str,
  }
}

export function NewBigintCmd(resultSlot: JSValueRef, value: bigint): NewBigintCommand {
  return {
    kind: NEW_BIGINT,
    resultSlot,
    value,
  }
}

export function NewFuncCmd(resultSlot: JSValueRef, arity: number, isConstructor: number, name: string, hostRefId: HostRefId): NewFuncCommand {
  return {
    kind: NEW_FUNC,
    resultSlot,
    arity,
    isConstructor,
    name,
    hostRefId,
  }
}

export function SetStrValueCmd(targetSlot: JSValueRef, valueSlot: JSValueRef, flags: SetPropFlags, key: string): SetStrValueCommand {
  return {
    kind: SET_STR_VALUE,
    targetSlot,
    valueSlot,
    flags,
    key,
  }
}

export function SetStrNullCmd(targetSlot: JSValueRef, flags: SetPropFlags, key: string): SetStrNullCommand {
  return {
    kind: SET_STR_NULL,
    targetSlot,
    flags,
    key,
  }
}

export function SetStrUndefCmd(targetSlot: JSValueRef, flags: SetPropFlags, key: string): SetStrUndefCommand {
  return {
    kind: SET_STR_UNDEF,
    targetSlot,
    flags,
    key,
  }
}

export function SetStrBoolCmd(targetSlot: JSValueRef, boolVal: number, flags: SetPropFlags, key: string): SetStrBoolCommand {
  return {
    kind: SET_STR_BOOL,
    targetSlot,
    boolVal,
    flags,
    key,
  }
}

export function SetStrInt32Cmd(targetSlot: JSValueRef, flags: SetPropFlags, key: string, intVal: number): SetStrInt32Command {
  return {
    kind: SET_STR_INT32,
    targetSlot,
    flags,
    key,
    intVal,
  }
}

export function SetStrF64Cmd(targetSlot: JSValueRef, flags: SetPropFlags, f64Val: number, key: string): SetStrF64Command {
  return {
    kind: SET_STR_F64,
    targetSlot,
    flags,
    f64Val,
    key,
  }
}

export function SetStrBigintCmd(targetSlot: JSValueRef, flags: SetPropFlags, i64Val: bigint, key: string): SetStrBigintCommand {
  return {
    kind: SET_STR_BIGINT,
    targetSlot,
    flags,
    i64Val,
    key,
  }
}

export function SetStrStringCmd(targetSlot: JSValueRef, flags: SetPropFlags, str: string, key: string): SetStrStringCommand {
  return {
    kind: SET_STR_STRING,
    targetSlot,
    flags,
    str,
    key,
  }
}

export function SetIdxValueCmd(targetSlot: JSValueRef, valueSlot: JSValueRef, flags: SetPropFlags, index: number): SetIdxValueCommand {
  return {
    kind: SET_IDX_VALUE,
    targetSlot,
    valueSlot,
    flags,
    index,
  }
}

export function SetIdxNullCmd(targetSlot: JSValueRef, flags: SetPropFlags, index: number): SetIdxNullCommand {
  return {
    kind: SET_IDX_NULL,
    targetSlot,
    flags,
    index,
  }
}

export function SetIdxUndefCmd(targetSlot: JSValueRef, flags: SetPropFlags, index: number): SetIdxUndefCommand {
  return {
    kind: SET_IDX_UNDEF,
    targetSlot,
    flags,
    index,
  }
}

export function SetIdxBoolCmd(targetSlot: JSValueRef, boolVal: number, flags: SetPropFlags, index: number): SetIdxBoolCommand {
  return {
    kind: SET_IDX_BOOL,
    targetSlot,
    boolVal,
    flags,
    index,
  }
}

export function SetIdxInt32Cmd(targetSlot: JSValueRef, flags: SetPropFlags, index: number, intVal: number): SetIdxInt32Command {
  return {
    kind: SET_IDX_INT32,
    targetSlot,
    flags,
    index,
    intVal,
  }
}

export function SetIdxF64Cmd(targetSlot: JSValueRef, flags: SetPropFlags, f64Val: number, index: number): SetIdxF64Command {
  return {
    kind: SET_IDX_F64,
    targetSlot,
    flags,
    f64Val,
    index,
  }
}

export function SetIdxBigintCmd(targetSlot: JSValueRef, flags: SetPropFlags, i64Val: bigint, index: number): SetIdxBigintCommand {
  return {
    kind: SET_IDX_BIGINT,
    targetSlot,
    flags,
    i64Val,
    index,
  }
}

export function SetIdxStringCmd(targetSlot: JSValueRef, flags: SetPropFlags, str: string, index: number): SetIdxStringCommand {
  return {
    kind: SET_IDX_STRING,
    targetSlot,
    flags,
    str,
    index,
  }
}

export function SetCmd(targetSlot: JSValueRef, keySlot: JSValueRef, valueSlot: JSValueRef, flags: SetPropFlags): SetCommand {
  return {
    kind: SET,
    targetSlot,
    keySlot,
    valueSlot,
    flags,
  }
}

export function DefGetsetCmd(targetSlot: JSValueRef, flags: JSPropFlags, getterRef: HostRefId, setterRef: HostRefId, key: string): DefGetsetCommand {
  return {
    kind: DEF_GETSET,
    targetSlot,
    flags,
    getterRef,
    setterRef,
    key,
  }
}

export function GetCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, keySlot: JSValueRef): GetCommand {
  return {
    kind: GET,
    resultSlot,
    sourceSlot,
    keySlot,
  }
}

export function GetStrCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, key: string): GetStrCommand {
  return {
    kind: GET_STR,
    resultSlot,
    sourceSlot,
    key,
  }
}

export function GetIdxCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, index: number): GetIdxCommand {
  return {
    kind: GET_IDX,
    resultSlot,
    sourceSlot,
    index,
  }
}

export function GlobalCmd(resultSlot: JSValueRef): GlobalCommand {
  return {
    kind: GLOBAL,
    resultSlot,
  }
}

export function GlobalGetStrCmd(resultSlot: JSValueRef, key: string): GlobalGetStrCommand {
  return {
    kind: GLOBAL_GET_STR,
    resultSlot,
    key,
  }
}

export function GlobalSetStrCmd(valueSlot: JSValueRef, flags: JSPropFlags, key: string): GlobalSetStrCommand {
  return {
    kind: GLOBAL_SET_STR,
    valueSlot,
    flags,
    key,
  }
}

export function MapSetCmd(targetSlot: JSValueRef, keySlot: JSValueRef, valueSlot: JSValueRef): MapSetCommand {
  return {
    kind: MAP_SET,
    targetSlot,
    keySlot,
    valueSlot,
  }
}

export function MapSetStrCmd(targetSlot: JSValueRef, valueSlot: JSValueRef, key: string): MapSetStrCommand {
  return {
    kind: MAP_SET_STR,
    targetSlot,
    valueSlot,
    key,
  }
}

export function SetAddCmd(targetSlot: JSValueRef, valueSlot: JSValueRef): SetAddCommand {
  return {
    kind: SET_ADD,
    targetSlot,
    valueSlot,
  }
}

export function CallCmd(resultSlot: JSValueRef, funcSlot: JSValueRef, thisSlot: JSValueRef, argv: readonly JSValueRef[]): CallCommand {
  return {
    kind: CALL,
    barrier: true,
    resultSlot,
    funcSlot,
    thisSlot,
    argv,
  }
}

export function CallCtorCmd(resultSlot: JSValueRef, ctorSlot: JSValueRef, argv: readonly JSValueRef[]): CallCtorCommand {
  return {
    kind: CALL_CTOR,
    barrier: true,
    resultSlot,
    ctorSlot,
    argv,
  }
}

export function EvalCmd(resultSlot: JSValueRef, callFlags: EvalFlags, code: string, filename: string): EvalCommand {
  return {
    kind: EVAL,
    barrier: true,
    resultSlot,
    callFlags,
    code,
    filename,
  }
}

export function ThrowCmd(errorSlot: JSValueRef): ThrowCommand {
  return {
    kind: THROW,
    errorSlot,
  }
}

export function ResolveExcCmd(resultSlot: JSValueRef, maybeExcSlot: JSValueRef): ResolveExcCommand {
  return {
    kind: RESOLVE_EXC,
    resultSlot,
    maybeExcSlot,
  }
}

export function DupCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef): DupCommand {
  return {
    kind: DUP,
    resultSlot,
    sourceSlot,
  }
}

export function DupPtrCmd(resultSlot: JSValueRef, valuePtr: JSValueRef): DupPtrCommand {
  return {
    kind: DUP_PTR,
    resultSlot,
    valuePtr,
  }
}

export function FreeCmd(targetSlot: JSValueRef): FreeCommand {
  return {
    kind: FREE,
    targetSlot,
  }
}

export function FreePtrCmd(valuePtr: JSValueRef): FreePtrCommand {
  return {
    kind: FREE_PTR,
    valuePtr,
  }
}

export function BytecodeWriteCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, flags: number): BytecodeWriteCommand {
  return {
    kind: BYTECODE_WRITE,
    resultSlot,
    sourceSlot,
    flags,
  }
}

export function BytecodeReadCmd(resultSlot: JSValueRef, sourceSlot: JSValueRef, flags: number): BytecodeReadCommand {
  return {
    kind: BYTECODE_READ,
    resultSlot,
    sourceSlot,
    flags,
  }
}

export function FunclistNewCmd(resultFunclistSlot: FuncListRef, count: number): FunclistNewCommand {
  return {
    kind: FUNCLIST_NEW,
    resultFunclistSlot,
    count,
  }
}

export function FunclistAssignCmd(targetSlot: JSValueRef, sourceFunclistSlot: FuncListRef): FunclistAssignCommand {
  return {
    kind: FUNCLIST_ASSIGN,
    targetSlot,
    sourceFunclistSlot,
  }
}

export function FunclistFreeCmd(targetFunclistSlot: FuncListRef): FunclistFreeCommand {
  return {
    kind: FUNCLIST_FREE,
    targetFunclistSlot,
  }
}

export function FunclistDefCfuncCmd(targetFunclistSlot: FuncListRef, arity: number, flags: JSPropFlags, index: number, funcName: string, cFuncPtr: JSCFunctionTypePointer): FunclistDefCfuncCommand {
  return {
    kind: FUNCLIST_DEF_CFUNC,
    targetFunclistSlot,
    arity,
    flags,
    index,
    funcName,
    cFuncPtr,
  }
}

export function FunclistDefCfuncCtorCmd(targetFunclistSlot: FuncListRef, arity: number, flags: JSPropFlags, index: number, funcName: string, cFuncPtr: JSCFunctionTypePointer): FunclistDefCfuncCtorCommand {
  return {
    kind: FUNCLIST_DEF_CFUNC_CTOR,
    targetFunclistSlot,
    arity,
    flags,
    index,
    funcName,
    cFuncPtr,
  }
}

export function FunclistDefCgetsetCmd(targetFunclistSlot: FuncListRef, index: number, flags: JSPropFlags, key: string, getterPtr: JSCFunctionTypePointer, setterPtr: JSCFunctionTypePointer): FunclistDefCgetsetCommand {
  return {
    kind: FUNCLIST_DEF_CGETSET,
    targetFunclistSlot,
    index,
    flags,
    key,
    getterPtr,
    setterPtr,
  }
}

export function FunclistDefStringCmd(targetFunclistSlot: FuncListRef, index: number, flags: JSPropFlags, str: string, name: string): FunclistDefStringCommand {
  return {
    kind: FUNCLIST_DEF_STRING,
    targetFunclistSlot,
    index,
    flags,
    str,
    name,
  }
}

export function FunclistDefInt32Cmd(targetFunclistSlot: FuncListRef, flags: JSPropFlags, index: number, intVal: number, key: string): FunclistDefInt32Command {
  return {
    kind: FUNCLIST_DEF_INT32,
    targetFunclistSlot,
    flags,
    index,
    intVal,
    key,
  }
}

export function FunclistDefInt64Cmd(targetFunclistSlot: FuncListRef, index: number, flags: JSPropFlags, i64Val: bigint, name: string): FunclistDefInt64Command {
  return {
    kind: FUNCLIST_DEF_INT64,
    targetFunclistSlot,
    index,
    flags,
    i64Val,
    name,
  }
}

export function FunclistDefDoubleCmd(targetFunclistSlot: FuncListRef, index: number, flags: JSPropFlags, f64Val: number, key: string): FunclistDefDoubleCommand {
  return {
    kind: FUNCLIST_DEF_DOUBLE,
    targetFunclistSlot,
    index,
    flags,
    f64Val,
    key,
  }
}

export function FunclistDefNullCmd(targetFunclistSlot: FuncListRef, flags: JSPropFlags, key: string, index: number): FunclistDefNullCommand {
  return {
    kind: FUNCLIST_DEF_NULL,
    targetFunclistSlot,
    flags,
    key,
    index,
  }
}

export function FunclistDefUndefinedCmd(targetFunclistSlot: FuncListRef, flags: JSPropFlags, key: string, index: number): FunclistDefUndefinedCommand {
  return {
    kind: FUNCLIST_DEF_UNDEFINED,
    targetFunclistSlot,
    flags,
    key,
    index,
  }
}

export function FunclistDefObjectCmd(targetFunclistSlot: FuncListRef, objectFunclistSlot: FuncListRef, flags: JSPropFlags, key: string, index: number): FunclistDefObjectCommand {
  return {
    kind: FUNCLIST_DEF_OBJECT,
    targetFunclistSlot,
    objectFunclistSlot,
    flags,
    key,
    index,
  }
}

export type RefVisitor = (ref: AnyRef) => void

export function forEachReadRef(command: Command, visit: RefVisitor): void {
  switch (command.kind) {
    case NEW_OBJECT_PROTO:
      visit(command.protoSlot)
      return
    case NEW_TYPED_ARRAY:
    case GET_STR:
    case GET_IDX:
    case DUP:
    case BYTECODE_WRITE:
    case BYTECODE_READ:
      visit(command.sourceSlot)
      return
    case SET_STR_VALUE:
    case SET_IDX_VALUE:
    case MAP_SET_STR:
    case SET_ADD:
      visit(command.targetSlot)
      visit(command.valueSlot)
      return
    case SET_STR_NULL:
    case SET_STR_UNDEF:
    case SET_STR_BOOL:
    case SET_STR_INT32:
    case SET_STR_F64:
    case SET_STR_BIGINT:
    case SET_STR_STRING:
    case SET_IDX_NULL:
    case SET_IDX_UNDEF:
    case SET_IDX_BOOL:
    case SET_IDX_INT32:
    case SET_IDX_F64:
    case SET_IDX_BIGINT:
    case SET_IDX_STRING:
    case DEF_GETSET:
    case FREE:
      visit(command.targetSlot)
      return
    case SET:
    case MAP_SET:
      visit(command.targetSlot)
      visit(command.keySlot)
      visit(command.valueSlot)
      return
    case GET:
      visit(command.sourceSlot)
      visit(command.keySlot)
      return
    case GLOBAL_SET_STR:
      visit(command.valueSlot)
      return
    case CALL:
      visit(command.funcSlot)
      visit(command.thisSlot)
      command.argv.forEach(visit)
      return
    case CALL_CTOR:
      visit(command.ctorSlot)
      command.argv.forEach(visit)
      return
    case THROW:
      visit(command.errorSlot)
      return
    case RESOLVE_EXC:
      visit(command.maybeExcSlot)
      return
    case DUP_PTR:
    case FREE_PTR:
      visit(command.valuePtr)
      return
    case FUNCLIST_ASSIGN:
      visit(command.targetSlot)
      visit(command.sourceFunclistSlot)
      return
    case FUNCLIST_FREE:
    case FUNCLIST_DEF_CFUNC:
    case FUNCLIST_DEF_CFUNC_CTOR:
    case FUNCLIST_DEF_CGETSET:
    case FUNCLIST_DEF_STRING:
    case FUNCLIST_DEF_INT32:
    case FUNCLIST_DEF_INT64:
    case FUNCLIST_DEF_DOUBLE:
    case FUNCLIST_DEF_NULL:
    case FUNCLIST_DEF_UNDEFINED:
      visit(command.targetFunclistSlot)
      return
    case FUNCLIST_DEF_OBJECT:
      visit(command.targetFunclistSlot)
      visit(command.objectFunclistSlot)
      return
    default:
      return
  }
}

export function forEachWriteRef(command: Command, visit: RefVisitor): void {
  switch (command.kind) {
    case NEW_OBJECT:
    case NEW_OBJECT_PROTO:
    case NEW_ARRAY:
    case NEW_MAP:
    case NEW_SET:
    case NEW_DATE:
    case NEW_ERROR:
    case NEW_ARRAYBUFFER:
    case NEW_TYPED_ARRAY:
    case NEW_SYMBOL:
    case NEW_FLOAT64:
    case NEW_STRING:
    case NEW_BIGINT:
    case NEW_FUNC:
    case GET:
    case GET_STR:
    case GET_IDX:
    case GLOBAL:
    case GLOBAL_GET_STR:
    case CALL:
    case CALL_CTOR:
    case EVAL:
    case RESOLVE_EXC:
    case DUP:
    case DUP_PTR:
    case BYTECODE_WRITE:
    case BYTECODE_READ:
      visit(command.resultSlot)
      return
    case FUNCLIST_NEW:
      visit(command.resultFunclistSlot)
      return
    default:
      return
  }
}

// =============================================================================

// Setter Helpers

// =============================================================================



function setOpcode(view: DataView, offset: number, opcode: number): void {
  view.setUint8(offset + 0, opcode)
}

function setSlotA(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 1, slot)
}

function setSlotB(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 2, slot)
}

function setSlotC(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 3, slot)
}

function setD1_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 4, value, true)
}

function setD2_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 8, value, true)
}

function setD2_i32(view: DataView, offset: number, value: number): void {
  view.setInt32(offset + 8, value, true)
}

function setD3_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 12, value, true)
}

function setD3_i32(view: DataView, offset: number, value: number): void {
  view.setInt32(offset + 12, value, true)
}

function setData_f64(view: DataView, offset: number, value: number): void {
  view.setFloat64(offset + 4, value, true)
}

function setData_i64(view: DataView, offset: number, value: bigint): void {
  view.setBigInt64(offset + 4, value, true)
}

function writePattern0(view: DataView, offset: CommandPtr, p0: JSValueSlot): void {
  setSlotA(view, offset, p0)
}

function writePattern1(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: JSValueSlot): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
}

function writePattern2(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: Float64): void {
  setSlotA(view, offset, p0)
  setData_f64(view, offset, p1)
}

function writePattern4(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: BorrowedHeapCharPointer, p2: Uint32): void {
  setSlotA(view, offset, p0)
  setD1_u32(view, offset, p1)
  setD2_u32(view, offset, p2)
}

function writePattern10(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: SetPropFlags, p2: BorrowedHeapCharPointer, p3: Uint32): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
}

function writePattern17(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: SetPropFlags, p2: Uint32): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
}

function writePattern25(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: JSValueSlot, p2: JSValueSlot): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setSlotC(view, offset, p2)
}

function writePattern26(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: JSValueSlot, p2: BorrowedHeapCharPointer, p3: Uint32): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
}

function writePattern27(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: JSValueSlot, p2: Uint32): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setD1_u32(view, offset, p2)
}

function writePattern37(view: DataView, offset: CommandPtr, p0: FuncListSlot, p1: Uint8, p2: JSPropFlags, p3: Uint32, p4: BorrowedHeapCharPointer, p5: JSCFunctionTypePointer): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setSlotC(view, offset, p2)
  setD1_u32(view, offset, p3)
  setD2_u32(view, offset, p4)
  setD3_u32(view, offset, p5)
}

function writePattern43(view: DataView, offset: CommandPtr, p0: FuncListSlot, p1: JSPropFlags, p2: BorrowedHeapCharPointer, p3: Uint32, p4: Uint32): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
  setD3_u32(view, offset, p4)
}

// =============================================================================

// Writer Functions (generated)

// =============================================================================



export function writeInvalid(view: DataView, offset: CommandPtr): void {
  setOpcode(view, offset, 0)
}

export function writeNewObject(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 1)
  writePattern0(view, offset, result_slot)
}

export function writeNewObjectProto(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, proto_slot: JSValueSlot): void {
  setOpcode(view, offset, 2)
  writePattern1(view, offset, result_slot, proto_slot)
}

export function writeNewArray(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 3)
  writePattern0(view, offset, result_slot)
}

export function writeNewMap(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 4)
  writePattern0(view, offset, result_slot)
}

export function writeNewSet(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 5)
  writePattern0(view, offset, result_slot)
}

export function writeNewDate(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, timestamp: Float64): void {
  setOpcode(view, offset, 6)
  writePattern2(view, offset, result_slot, timestamp)
}

export function writeNewError(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, maybe_name_len: Uint8, new_error_flags: NewErrorFlags, message_ptr: BorrowedHeapCharPointer, message_len: Uint32, name_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 7)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, maybe_name_len)
  setSlotC(view, offset, new_error_flags)
  setD1_u32(view, offset, message_ptr)
  setD2_u32(view, offset, message_len)
  setD3_u32(view, offset, name_ptr)
}

export function writeNewArraybuffer(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, data_ptr: BorrowedHeapCharPointer, data_len: Uint32): void {
  setOpcode(view, offset, 8)
  writePattern4(view, offset, result_slot, data_ptr, data_len)
}

export function writeNewTypedArray(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, array_type: NewTypedArrayFlags, source_offset: Uint32, length: Uint32): void {
  setOpcode(view, offset, 9)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, source_slot)
  setSlotC(view, offset, array_type)
  setD1_u32(view, offset, source_offset)
  setD2_u32(view, offset, length)
}

export function writeNewSymbol(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, is_global: Uint8, desc_ptr: BorrowedHeapCharPointer, desc_len: Uint32): void {
  setOpcode(view, offset, 10)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, is_global)
  setD1_u32(view, offset, desc_ptr)
  setD2_u32(view, offset, desc_len)
}

export function writeNewFloat64(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, value: Float64): void {
  setOpcode(view, offset, 11)
  writePattern2(view, offset, result_slot, value)
}

export function writeNewString(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, str_ptr: BorrowedHeapCharPointer, str_len: Uint32): void {
  setOpcode(view, offset, 12)
  writePattern4(view, offset, result_slot, str_ptr, str_len)
}

export function writeNewBigint(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, value: Int64): void {
  setOpcode(view, offset, 13)
  setSlotA(view, offset, result_slot)
  setData_i64(view, offset, value)
}

export function writeNewFunc(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, arity: Uint8, is_constructor: Uint8, name_ptr: BorrowedHeapCharPointer, name_len: Uint32, host_ref_id: HostRefId): void {
  setOpcode(view, offset, 14)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, arity)
  setSlotC(view, offset, is_constructor)
  setD1_u32(view, offset, name_ptr)
  setD2_u32(view, offset, name_len)
  setD3_u32(view, offset, host_ref_id)
}

export function writeSetStrValue(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, value_slot: JSValueSlot, flags: SetPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 15)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeSetStrNull(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 16)
  writePattern10(view, offset, target_slot, flags, key_ptr, key_len)
}

export function writeSetStrUndef(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 17)
  writePattern10(view, offset, target_slot, flags, key_ptr, key_len)
}

export function writeSetStrBool(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, bool_val: Uint8, flags: SetPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 18)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, bool_val)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeSetStrInt32(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32, int_val: Int32): void {
  setOpcode(view, offset, 19)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
  setD3_i32(view, offset, int_val)
}

export function writeSetStrF64(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, maybe_key_len: Uint8, flags: SetPropFlags, f64_val: Float64, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 20)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetStrBigint(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, maybe_key_len: Uint8, flags: SetPropFlags, i64_val: Int64, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 21)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetStrString(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, maybe_key_len: Uint8, flags: SetPropFlags, str_ptr: BorrowedHeapCharPointer, str_len: Uint32, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 22)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetIdxValue(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, value_slot: JSValueSlot, flags: SetPropFlags, index: Uint32): void {
  setOpcode(view, offset, 23)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
}

export function writeSetIdxNull(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, index: Uint32): void {
  setOpcode(view, offset, 24)
  writePattern17(view, offset, target_slot, flags, index)
}

export function writeSetIdxUndef(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, index: Uint32): void {
  setOpcode(view, offset, 25)
  writePattern17(view, offset, target_slot, flags, index)
}

export function writeSetIdxBool(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, bool_val: Uint8, flags: SetPropFlags, index: Uint32): void {
  setOpcode(view, offset, 26)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, bool_val)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
}

export function writeSetIdxInt32(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, index: Uint32, int_val: Int32): void {
  setOpcode(view, offset, 27)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
  setD2_i32(view, offset, int_val)
}

export function writeSetIdxF64(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, f64_val: Float64, index: Uint32): void {
  setOpcode(view, offset, 28)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, index)
}

export function writeSetIdxBigint(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, i64_val: Int64, index: Uint32): void {
  setOpcode(view, offset, 29)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, index)
}

export function writeSetIdxString(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, flags: SetPropFlags, str_ptr: BorrowedHeapCharPointer, str_len: Uint32, index: Uint32): void {
  setOpcode(view, offset, 30)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, index)
}

export function writeSet(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, key_slot: JSValueSlot, value_slot: JSValueSlot, flags: SetPropFlags): void {
  setOpcode(view, offset, 31)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, key_slot)
  setSlotC(view, offset, value_slot)
  setD1_u32(view, offset, flags)
}

export function writeDefGetset(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, maybe_key_len: Uint8, flags: JSPropFlags, getter_ref: HostRefId, setter_ref: HostRefId, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 32)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, getter_ref)
  setD2_u32(view, offset, setter_ref)
  setD3_u32(view, offset, key_ptr)
}

export function writeGet(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, key_slot: JSValueSlot): void {
  setOpcode(view, offset, 33)
  writePattern25(view, offset, result_slot, source_slot, key_slot)
}

export function writeGetStr(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 34)
  writePattern26(view, offset, result_slot, source_slot, key_ptr, key_len)
}

export function writeGetIdx(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, index: Uint32): void {
  setOpcode(view, offset, 35)
  writePattern27(view, offset, result_slot, source_slot, index)
}

export function writeGlobal(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 36)
  writePattern0(view, offset, result_slot)
}

export function writeGlobalGetStr(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 37)
  writePattern4(view, offset, result_slot, key_ptr, key_len)
}

export function writeGlobalSetStr(view: DataView, offset: CommandPtr, value_slot: JSValueSlot, flags: JSPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 38)
  setSlotA(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeMapSet(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, key_slot: JSValueSlot, value_slot: JSValueSlot): void {
  setOpcode(view, offset, 39)
  writePattern25(view, offset, target_slot, key_slot, value_slot)
}

export function writeMapSetStr(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, value_slot: JSValueSlot, key_ptr: BorrowedHeapCharPointer, key_len: Uint32): void {
  setOpcode(view, offset, 40)
  writePattern26(view, offset, target_slot, value_slot, key_ptr, key_len)
}

export function writeSetAdd(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, value_slot: JSValueSlot): void {
  setOpcode(view, offset, 41)
  writePattern1(view, offset, target_slot, value_slot)
}

export function writeCall(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, func_slot: JSValueSlot, this_slot: JSValueSlot, argv: JSValuePointer, argc: Uint32): void {
  setOpcode(view, offset, 42)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, func_slot)
  setSlotC(view, offset, this_slot)
  setD1_u32(view, offset, argv)
  setD2_u32(view, offset, argc)
}

export function writeCallCtor(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, ctor_slot: JSValueSlot, argv: JSValuePointer, argc: Uint32): void {
  setOpcode(view, offset, 43)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, ctor_slot)
  setD1_u32(view, offset, argv)
  setD2_u32(view, offset, argc)
}

export function writeEval(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, maybe_filename_len: Uint8, call_flags: EvalFlags, code_ptr: BorrowedHeapCharPointer, code_len: Uint32, filename: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 44)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, maybe_filename_len)
  setSlotC(view, offset, call_flags)
  setD1_u32(view, offset, code_ptr)
  setD2_u32(view, offset, code_len)
  setD3_u32(view, offset, filename)
}

export function writeThrow(view: DataView, offset: CommandPtr, error_slot: JSValueSlot): void {
  setOpcode(view, offset, 45)
  writePattern0(view, offset, error_slot)
}

export function writeResolveExc(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, maybe_exc_slot: JSValueSlot): void {
  setOpcode(view, offset, 46)
  writePattern1(view, offset, result_slot, maybe_exc_slot)
}

export function writeDup(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot): void {
  setOpcode(view, offset, 47)
  writePattern1(view, offset, result_slot, source_slot)
}

export function writeDupPtr(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, value_ptr: JSValuePointer): void {
  setOpcode(view, offset, 48)
  setSlotA(view, offset, result_slot)
  setD1_u32(view, offset, value_ptr)
}

export function writeFree(view: DataView, offset: CommandPtr, target_slot: JSValueSlot): void {
  setOpcode(view, offset, 49)
  writePattern0(view, offset, target_slot)
}

export function writeFreePtr(view: DataView, offset: CommandPtr, value_ptr: JSValuePointer): void {
  setOpcode(view, offset, 50)
  setD1_u32(view, offset, value_ptr)
}

export function writeBytecodeWrite(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, flags: Uint32): void {
  setOpcode(view, offset, 51)
  writePattern27(view, offset, result_slot, source_slot, flags)
}

export function writeBytecodeRead(view: DataView, offset: CommandPtr, result_slot: JSValueSlot, source_slot: JSValueSlot, flags: Uint32): void {
  setOpcode(view, offset, 52)
  writePattern27(view, offset, result_slot, source_slot, flags)
}

export function writeFunclistNew(view: DataView, offset: CommandPtr, result_funclist_slot: FuncListSlot, count: Uint32): void {
  setOpcode(view, offset, 53)
  setSlotA(view, offset, result_funclist_slot)
  setD1_u32(view, offset, count)
}

export function writeFunclistAssign(view: DataView, offset: CommandPtr, target_slot: JSValueSlot, source_funclist_slot: FuncListSlot): void {
  setOpcode(view, offset, 54)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, source_funclist_slot)
}

export function writeFunclistFree(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot): void {
  setOpcode(view, offset, 55)
  setSlotA(view, offset, target_funclist_slot)
}

export function writeFunclistDefCfunc(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, arity: Uint8, flags: JSPropFlags, index: Uint32, func_name_ptr: BorrowedHeapCharPointer, c_func_ptr: JSCFunctionTypePointer): void {
  setOpcode(view, offset, 56)
  writePattern37(view, offset, target_funclist_slot, arity, flags, index, func_name_ptr, c_func_ptr)
}

export function writeFunclistDefCfuncCtor(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, arity: Uint8, flags: JSPropFlags, index: Uint32, func_name_ptr: BorrowedHeapCharPointer, c_func_ptr: JSCFunctionTypePointer): void {
  setOpcode(view, offset, 57)
  writePattern37(view, offset, target_funclist_slot, arity, flags, index, func_name_ptr, c_func_ptr)
}

export function writeFunclistDefCgetset(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, index: Uint8, flags: JSPropFlags, key_ptr: BorrowedHeapCharPointer, getter_ptr: JSCFunctionTypePointer, setter_ptr: JSCFunctionTypePointer): void {
  setOpcode(view, offset, 58)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, getter_ptr)
  setD3_u32(view, offset, setter_ptr)
}

export function writeFunclistDefString(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, index: Uint8, flags: JSPropFlags, str_ptr: BorrowedHeapCharPointer, str_len: Uint32, name_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 59)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, name_ptr)
}

export function writeFunclistDefInt32(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, maybe_key_len: Uint8, flags: JSPropFlags, index: Uint32, int_val: Int32, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 60)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
  setD2_i32(view, offset, int_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeFunclistDefInt64(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, index: Uint8, flags: JSPropFlags, i64_val: Int64, name_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 61)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, name_ptr)
}

export function writeFunclistDefDouble(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, index: Uint8, flags: JSPropFlags, f64_val: Float64, key_ptr: BorrowedHeapCharPointer): void {
  setOpcode(view, offset, 62)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeFunclistDefNull(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, flags: JSPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32, index: Uint32): void {
  setOpcode(view, offset, 63)
  writePattern43(view, offset, target_funclist_slot, flags, key_ptr, key_len, index)
}

export function writeFunclistDefUndefined(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, flags: JSPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32, index: Uint32): void {
  setOpcode(view, offset, 64)
  writePattern43(view, offset, target_funclist_slot, flags, key_ptr, key_len, index)
}

export function writeFunclistDefObject(view: DataView, offset: CommandPtr, target_funclist_slot: FuncListSlot, object_funclist_slot: FuncListSlot, flags: JSPropFlags, key_ptr: BorrowedHeapCharPointer, key_len: Uint32, index: Uint32): void {
  setOpcode(view, offset, 65)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, object_funclist_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
  setD3_u32(view, offset, index)
}

export const OP_ENCODERS = [
  writeInvalid,
  writeNewObject,
  writeNewObjectProto,
  writeNewArray,
  writeNewMap,
  writeNewSet,
  writeNewDate,
  writeNewError,
  writeNewArraybuffer,
  writeNewTypedArray,
  writeNewSymbol,
  writeNewFloat64,
  writeNewString,
  writeNewBigint,
  writeNewFunc,
  writeSetStrValue,
  writeSetStrNull,
  writeSetStrUndef,
  writeSetStrBool,
  writeSetStrInt32,
  writeSetStrF64,
  writeSetStrBigint,
  writeSetStrString,
  writeSetIdxValue,
  writeSetIdxNull,
  writeSetIdxUndef,
  writeSetIdxBool,
  writeSetIdxInt32,
  writeSetIdxF64,
  writeSetIdxBigint,
  writeSetIdxString,
  writeSet,
  writeDefGetset,
  writeGet,
  writeGetStr,
  writeGetIdx,
  writeGlobal,
  writeGlobalGetStr,
  writeGlobalSetStr,
  writeMapSet,
  writeMapSetStr,
  writeSetAdd,
  writeCall,
  writeCallCtor,
  writeEval,
  writeThrow,
  writeResolveExc,
  writeDup,
  writeDupPtr,
  writeFree,
  writeFreePtr,
  writeBytecodeWrite,
  writeBytecodeRead,
  writeFunclistNew,
  writeFunclistAssign,
  writeFunclistFree,
  writeFunclistDefCfunc,
  writeFunclistDefCfuncCtor,
  writeFunclistDefCgetset,
  writeFunclistDefString,
  writeFunclistDefInt32,
  writeFunclistDefInt64,
  writeFunclistDefDouble,
  writeFunclistDefNull,
  writeFunclistDefUndefined,
  writeFunclistDefObject,
] as const
