// This file is generated by scripts/generate.ts ops - do not edit manually

import type {
  AnySlot,
  BorrowedHeapCharPointer,
  CommandPtr,
  EvalFlags,
  Float64,
  FuncListSlot,
  HostRefId,
  Int32,
  Int64,
  JSCFunctionTypePointer,
  JSPropFlags,
  JSValuePointer,
  JSValueSlot,
  JSVoidPointer,
  NewErrorFlags,
  NewTypedArrayFlags,
  SetPropFlags,
  SlotType,
  Uint32,
  Uint8,
} from "@jitl/quickjs-ffi-types"
import type {
  CommandRef,
  CommandWriteHelpers,
  FuncListRef,
  JSValueRef,
  RefVisitor,
} from "./command-types"

export const INVALID = 0 as const
export const SLOT_STORE = 1 as const
export const SLOT_LOAD = 2 as const
export const SLOT_FREE = 3 as const
export const NEW_OBJECT = 4 as const
export const NEW_OBJECT_PROTO = 5 as const
export const NEW_ARRAY = 6 as const
export const NEW_MAP = 7 as const
export const NEW_SET = 8 as const
export const NEW_DATE = 9 as const
export const NEW_ERROR = 10 as const
export const NEW_ARRAYBUFFER = 11 as const
export const NEW_TYPED_ARRAY = 12 as const
export const NEW_SYMBOL = 13 as const
export const NEW_FLOAT64 = 14 as const
export const NEW_STRING = 15 as const
export const NEW_BIGINT_INT64 = 16 as const
export const NEW_BIGINT_STR = 17 as const
export const NEW_FUNC = 18 as const
export const SET_STR_VALUE = 19 as const
export const SET_STR_NULL = 20 as const
export const SET_STR_UNDEF = 21 as const
export const SET_STR_BOOL = 22 as const
export const SET_STR_INT32 = 23 as const
export const SET_STR_F64 = 24 as const
export const SET_STR_BIGINT = 25 as const
export const SET_STR_STRING = 26 as const
export const SET_IDX_VALUE = 27 as const
export const SET_IDX_NULL = 28 as const
export const SET_IDX_UNDEF = 29 as const
export const SET_IDX_BOOL = 30 as const
export const SET_IDX_INT32 = 31 as const
export const SET_IDX_F64 = 32 as const
export const SET_IDX_BIGINT = 33 as const
export const SET_IDX_STRING = 34 as const
export const SET_VALUE_VALUE = 35 as const
export const DEF_VALUE_GETSET = 36 as const
export const GET_VALUE = 37 as const
export const GET_STR = 38 as const
export const GET_IDX = 39 as const
export const GLOBAL = 40 as const
export const GLOBAL_GET_STR = 41 as const
export const GLOBAL_SET_STR = 42 as const
export const MAP_SET = 43 as const
export const MAP_SET_STR = 44 as const
export const SET_ADD = 45 as const
export const CALL = 46 as const
export const CALL_ARGV = 47 as const
export const EVAL = 48 as const
export const THROW = 49 as const
export const RESOLVE_EXC = 50 as const
export const BYTECODE_WRITE = 51 as const
export const BYTECODE_READ = 52 as const
export const FUNCLIST_NEW = 53 as const
export const FUNCLIST_ASSIGN = 54 as const
export const FUNCLIST_DEF_CFUNC = 55 as const
export const FUNCLIST_DEF_CFUNC_CTOR = 56 as const
export const FUNCLIST_DEF_CGETSET = 57 as const
export const FUNCLIST_DEF_STRING = 58 as const
export const FUNCLIST_DEF_INT32 = 59 as const
export const FUNCLIST_DEF_INT64 = 60 as const
export const FUNCLIST_DEF_DOUBLE = 61 as const
export const FUNCLIST_DEF_NULL = 62 as const
export const FUNCLIST_DEF_UNDEFINED = 63 as const
export const FUNCLIST_DEF_OBJECT = 64 as const
export const FUNCLIST_DEF_BOOL = 65 as const

interface BaseCommand {
  opcode: number
  label?: string
}

export interface InvalidCommand extends BaseCommand {
  opcode: typeof INVALID
}

export interface SlotStoreCommand extends BaseCommand {
  opcode: typeof SLOT_STORE
  inSlot: CommandRef
  inSlotType: SlotType
  outPtr: JSVoidPointer
}

export interface SlotLoadCommand extends BaseCommand {
  opcode: typeof SLOT_LOAD
  outSlot: CommandRef
  outSlotType: SlotType
  inPtr: JSVoidPointer
}

export interface SlotFreeCommand extends BaseCommand {
  opcode: typeof SLOT_FREE
  targetSlot: CommandRef
  targetSlotType: SlotType
}

export interface NewObjectCommand extends BaseCommand {
  opcode: typeof NEW_OBJECT
  resultSlot: JSValueRef
}

export interface NewObjectProtoCommand extends BaseCommand {
  opcode: typeof NEW_OBJECT_PROTO
  resultSlot: JSValueRef
  protoSlot: JSValueRef
}

export interface NewArrayCommand extends BaseCommand {
  opcode: typeof NEW_ARRAY
  resultSlot: JSValueRef
}

export interface NewMapCommand extends BaseCommand {
  opcode: typeof NEW_MAP
  resultSlot: JSValueRef
}

export interface NewSetCommand extends BaseCommand {
  opcode: typeof NEW_SET
  resultSlot: JSValueRef
}

export interface NewDateCommand extends BaseCommand {
  opcode: typeof NEW_DATE
  resultSlot: JSValueRef
  timestamp: Float64
}

export interface NewErrorCommand extends BaseCommand {
  opcode: typeof NEW_ERROR
  resultSlot: JSValueRef
  newErrorFlags: NewErrorFlags
  message: string
  name: string
}

export interface NewArraybufferCommand extends BaseCommand {
  opcode: typeof NEW_ARRAYBUFFER
  resultSlot: JSValueRef
  classIsSharedArrayBuffer: Uint8
  dataBytes: Uint8Array
}

export interface NewTypedArrayCommand extends BaseCommand {
  opcode: typeof NEW_TYPED_ARRAY
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  arrayType: NewTypedArrayFlags
  sourceOffset: Uint32
  length: Uint32
}

export interface NewSymbolCommand extends BaseCommand {
  opcode: typeof NEW_SYMBOL
  resultSlot: JSValueRef
  isGlobal: Uint8
  desc: string
}

export interface NewFloat64Command extends BaseCommand {
  opcode: typeof NEW_FLOAT64
  resultSlot: JSValueRef
  value: Float64
}

export interface NewStringCommand extends BaseCommand {
  opcode: typeof NEW_STRING
  resultSlot: JSValueRef
  str: string
}

export interface NewBigintInt64Command extends BaseCommand {
  opcode: typeof NEW_BIGINT_INT64
  resultSlot: JSValueRef
  value: Int64
}

export interface NewBigintStrCommand extends BaseCommand {
  opcode: typeof NEW_BIGINT_STR
  resultSlot: JSValueRef
  str: string
}

export interface NewFuncCommand extends BaseCommand {
  opcode: typeof NEW_FUNC
  resultSlot: JSValueRef
  arity: Uint8
  isConstructor: Uint8
  name: string
  hostRefId: HostRefId
}

export interface SetStrValueCommand extends BaseCommand {
  opcode: typeof SET_STR_VALUE
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrNullCommand extends BaseCommand {
  opcode: typeof SET_STR_NULL
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrUndefCommand extends BaseCommand {
  opcode: typeof SET_STR_UNDEF
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
}

export interface SetStrBoolCommand extends BaseCommand {
  opcode: typeof SET_STR_BOOL
  targetSlot: JSValueRef
  boolVal: Uint8
  flags: SetPropFlags
  key: string
}

export interface SetStrInt32Command extends BaseCommand {
  opcode: typeof SET_STR_INT32
  targetSlot: JSValueRef
  flags: SetPropFlags
  key: string
  intVal: Int32
}

export interface SetStrF64Command extends BaseCommand {
  opcode: typeof SET_STR_F64
  targetSlot: JSValueRef
  flags: SetPropFlags
  f64Val: Float64
  key: string
}

export interface SetStrBigintCommand extends BaseCommand {
  opcode: typeof SET_STR_BIGINT
  targetSlot: JSValueRef
  flags: SetPropFlags
  i64Val: Int64
  key: string
}

export interface SetStrStringCommand extends BaseCommand {
  opcode: typeof SET_STR_STRING
  targetSlot: JSValueRef
  flags: SetPropFlags
  str: string
  key: string
}

export interface SetIdxValueCommand extends BaseCommand {
  opcode: typeof SET_IDX_VALUE
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
  index: Uint32
}

export interface SetIdxNullCommand extends BaseCommand {
  opcode: typeof SET_IDX_NULL
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: Uint32
}

export interface SetIdxUndefCommand extends BaseCommand {
  opcode: typeof SET_IDX_UNDEF
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: Uint32
}

export interface SetIdxBoolCommand extends BaseCommand {
  opcode: typeof SET_IDX_BOOL
  targetSlot: JSValueRef
  boolVal: Uint8
  flags: SetPropFlags
  index: Uint32
}

export interface SetIdxInt32Command extends BaseCommand {
  opcode: typeof SET_IDX_INT32
  targetSlot: JSValueRef
  flags: SetPropFlags
  index: Uint32
  intVal: Int32
}

export interface SetIdxF64Command extends BaseCommand {
  opcode: typeof SET_IDX_F64
  targetSlot: JSValueRef
  flags: SetPropFlags
  f64Val: Float64
  index: Uint32
}

export interface SetIdxBigintCommand extends BaseCommand {
  opcode: typeof SET_IDX_BIGINT
  targetSlot: JSValueRef
  flags: SetPropFlags
  i64Val: Int64
  index: Uint32
}

export interface SetIdxStringCommand extends BaseCommand {
  opcode: typeof SET_IDX_STRING
  targetSlot: JSValueRef
  flags: SetPropFlags
  str: string
  index: Uint32
}

export interface SetValueValueCommand extends BaseCommand {
  opcode: typeof SET_VALUE_VALUE
  targetSlot: JSValueRef
  keySlot: JSValueRef
  valueSlot: JSValueRef
  flags: SetPropFlags
}

export interface DefValueGetsetCommand extends BaseCommand {
  opcode: typeof DEF_VALUE_GETSET
  targetSlot: JSValueRef
  flags: JSPropFlags
  getterRef: HostRefId
  setterRef: HostRefId
  key: string
}

export interface GetValueCommand extends BaseCommand {
  opcode: typeof GET_VALUE
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  keySlot: JSValueRef
}

export interface GetStrCommand extends BaseCommand {
  opcode: typeof GET_STR
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  key: string
}

export interface GetIdxCommand extends BaseCommand {
  opcode: typeof GET_IDX
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  index: Uint32
}

export interface GlobalCommand extends BaseCommand {
  opcode: typeof GLOBAL
  resultSlot: JSValueRef
}

export interface GlobalGetStrCommand extends BaseCommand {
  opcode: typeof GLOBAL_GET_STR
  resultSlot: JSValueRef
  key: string
}

export interface GlobalSetStrCommand extends BaseCommand {
  opcode: typeof GLOBAL_SET_STR
  valueSlot: JSValueRef
  flags: JSPropFlags
  key: string
}

export interface MapSetCommand extends BaseCommand {
  opcode: typeof MAP_SET
  targetSlot: JSValueRef
  keySlot: JSValueRef
  valueSlot: JSValueRef
}

export interface MapSetStrCommand extends BaseCommand {
  opcode: typeof MAP_SET_STR
  targetSlot: JSValueRef
  valueSlot: JSValueRef
  key: string
}

export interface SetAddCommand extends BaseCommand {
  opcode: typeof SET_ADD
  targetSlot: JSValueRef
  valueSlot: JSValueRef
}

export interface CallCommand extends BaseCommand {
  opcode: typeof CALL
  resultSlot: JSValueRef
  funcSlot: JSValueRef
  thisSlot: JSValueRef
  argc: Uint8
  arg1: JSValueRef
  arg2: JSValueRef
  arg3: JSValueRef
  arg4: JSValueRef
  arg5: JSValueRef
  arg6: JSValueRef
  arg7: JSValueRef
  arg8: JSValueRef
  arg9: JSValueRef
  arg10: JSValueRef
  callAsConstructor: Uint8
}

export interface CallArgvCommand extends BaseCommand {
  opcode: typeof CALL_ARGV
  resultSlot: JSValueRef
  funcSlot: JSValueRef
  thisSlot: JSValueRef
  argc: Uint32
  argv: JSValuePointer
  callAsConstructor: Uint32
}

export interface EvalCommand extends BaseCommand {
  opcode: typeof EVAL
  resultSlot: JSValueRef
  callFlags: EvalFlags
  code: string
  filename: string
}

export interface ThrowCommand extends BaseCommand {
  opcode: typeof THROW
  errorSlot: JSValueRef
}

export interface ResolveExcCommand extends BaseCommand {
  opcode: typeof RESOLVE_EXC
  resultSlot: JSValueRef
  maybeExcSlot: JSValueRef
}

export interface BytecodeWriteCommand extends BaseCommand {
  opcode: typeof BYTECODE_WRITE
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  flags: Uint32
}

export interface BytecodeReadCommand extends BaseCommand {
  opcode: typeof BYTECODE_READ
  resultSlot: JSValueRef
  sourceSlot: JSValueRef
  flags: Uint32
}

export interface FunclistNewCommand extends BaseCommand {
  opcode: typeof FUNCLIST_NEW
  resultFunclistSlot: FuncListRef
  count: Uint32
}

export interface FunclistAssignCommand extends BaseCommand {
  opcode: typeof FUNCLIST_ASSIGN
  targetSlot: JSValueRef
  sourceFunclistSlot: FuncListRef
}

export interface FunclistDefCfuncCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_CFUNC
  targetFunclistSlot: FuncListRef
  arity: Uint8
  flags: JSPropFlags
  index: Uint32
  funcName: string
  cFuncPtr: JSCFunctionTypePointer
}

export interface FunclistDefCfuncCtorCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_CFUNC_CTOR
  targetFunclistSlot: FuncListRef
  arity: Uint8
  flags: JSPropFlags
  index: Uint32
  funcName: string
  cFuncPtr: JSCFunctionTypePointer
}

export interface FunclistDefCgetsetCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_CGETSET
  targetFunclistSlot: FuncListRef
  index: Uint8
  flags: JSPropFlags
  key: string
  getterPtr: JSCFunctionTypePointer
  setterPtr: JSCFunctionTypePointer
}

export interface FunclistDefStringCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_STRING
  targetFunclistSlot: FuncListRef
  index: Uint8
  flags: JSPropFlags
  str: string
  name: string
}

export interface FunclistDefInt32Command extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_INT32
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  index: Uint32
  intVal: Int32
  key: string
}

export interface FunclistDefInt64Command extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_INT64
  targetFunclistSlot: FuncListRef
  index: Uint8
  flags: JSPropFlags
  i64Val: Int64
  name: string
}

export interface FunclistDefDoubleCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_DOUBLE
  targetFunclistSlot: FuncListRef
  index: Uint8
  flags: JSPropFlags
  f64Val: Float64
  key: string
}

export interface FunclistDefNullCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_NULL
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: Uint32
}

export interface FunclistDefUndefinedCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_UNDEFINED
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: Uint32
}

export interface FunclistDefObjectCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_OBJECT
  targetFunclistSlot: FuncListRef
  objectFunclistSlot: FuncListRef
  flags: JSPropFlags
  key: string
  index: Uint32
}

export interface FunclistDefBoolCommand extends BaseCommand {
  opcode: typeof FUNCLIST_DEF_BOOL
  targetFunclistSlot: FuncListRef
  flags: JSPropFlags
  index: Uint32
  boolVal: Int32
  key: string
}

export type Command =
  | InvalidCommand
  | SlotStoreCommand
  | SlotLoadCommand
  | SlotFreeCommand
  | NewObjectCommand
  | NewObjectProtoCommand
  | NewArrayCommand
  | NewMapCommand
  | NewSetCommand
  | NewDateCommand
  | NewErrorCommand
  | NewArraybufferCommand
  | NewTypedArrayCommand
  | NewSymbolCommand
  | NewFloat64Command
  | NewStringCommand
  | NewBigintInt64Command
  | NewBigintStrCommand
  | NewFuncCommand
  | SetStrValueCommand
  | SetStrNullCommand
  | SetStrUndefCommand
  | SetStrBoolCommand
  | SetStrInt32Command
  | SetStrF64Command
  | SetStrBigintCommand
  | SetStrStringCommand
  | SetIdxValueCommand
  | SetIdxNullCommand
  | SetIdxUndefCommand
  | SetIdxBoolCommand
  | SetIdxInt32Command
  | SetIdxF64Command
  | SetIdxBigintCommand
  | SetIdxStringCommand
  | SetValueValueCommand
  | DefValueGetsetCommand
  | GetValueCommand
  | GetStrCommand
  | GetIdxCommand
  | GlobalCommand
  | GlobalGetStrCommand
  | GlobalSetStrCommand
  | MapSetCommand
  | MapSetStrCommand
  | SetAddCommand
  | CallCommand
  | CallArgvCommand
  | EvalCommand
  | ThrowCommand
  | ResolveExcCommand
  | BytecodeWriteCommand
  | BytecodeReadCommand
  | FunclistNewCommand
  | FunclistAssignCommand
  | FunclistDefCfuncCommand
  | FunclistDefCfuncCtorCommand
  | FunclistDefCgetsetCommand
  | FunclistDefStringCommand
  | FunclistDefInt32Command
  | FunclistDefInt64Command
  | FunclistDefDoubleCommand
  | FunclistDefNullCommand
  | FunclistDefUndefinedCommand
  | FunclistDefObjectCommand
  | FunclistDefBoolCommand

export function InvalidCmd(): InvalidCommand {
  return {
    opcode: INVALID,
  }
}

export function SlotStoreCmd(
  inSlot: CommandRef,
  inSlotType: SlotType,
  outPtr: JSVoidPointer,
): SlotStoreCommand {
  return {
    opcode: SLOT_STORE,
    inSlot,
    inSlotType,
    outPtr,
  }
}

export function SlotLoadCmd(
  outSlot: CommandRef,
  outSlotType: SlotType,
  inPtr: JSVoidPointer,
): SlotLoadCommand {
  return {
    opcode: SLOT_LOAD,
    outSlot,
    outSlotType,
    inPtr,
  }
}

export function SlotFreeCmd(targetSlot: CommandRef, targetSlotType: SlotType): SlotFreeCommand {
  return {
    opcode: SLOT_FREE,
    targetSlot,
    targetSlotType,
  }
}

export function NewObjectCmd(resultSlot: JSValueRef): NewObjectCommand {
  return {
    opcode: NEW_OBJECT,
    resultSlot,
  }
}

export function NewObjectProtoCmd(
  resultSlot: JSValueRef,
  protoSlot: JSValueRef,
): NewObjectProtoCommand {
  return {
    opcode: NEW_OBJECT_PROTO,
    resultSlot,
    protoSlot,
  }
}

export function NewArrayCmd(resultSlot: JSValueRef): NewArrayCommand {
  return {
    opcode: NEW_ARRAY,
    resultSlot,
  }
}

export function NewMapCmd(resultSlot: JSValueRef): NewMapCommand {
  return {
    opcode: NEW_MAP,
    resultSlot,
  }
}

export function NewSetCmd(resultSlot: JSValueRef): NewSetCommand {
  return {
    opcode: NEW_SET,
    resultSlot,
  }
}

export function NewDateCmd(resultSlot: JSValueRef, timestamp: Float64): NewDateCommand {
  return {
    opcode: NEW_DATE,
    resultSlot,
    timestamp,
  }
}

export function NewErrorCmd(
  resultSlot: JSValueRef,
  newErrorFlags: NewErrorFlags,
  message: string,
  name: string,
): NewErrorCommand {
  return {
    opcode: NEW_ERROR,
    resultSlot,
    newErrorFlags,
    message,
    name,
  }
}

export function NewArraybufferCmd(
  resultSlot: JSValueRef,
  classIsSharedArrayBuffer: Uint8,
  dataBytes: Uint8Array,
): NewArraybufferCommand {
  return {
    opcode: NEW_ARRAYBUFFER,
    resultSlot,
    classIsSharedArrayBuffer,
    dataBytes,
  }
}

export function NewTypedArrayCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  arrayType: NewTypedArrayFlags,
  sourceOffset: Uint32,
  length: Uint32,
): NewTypedArrayCommand {
  return {
    opcode: NEW_TYPED_ARRAY,
    resultSlot,
    sourceSlot,
    arrayType,
    sourceOffset,
    length,
  }
}

export function NewSymbolCmd(
  resultSlot: JSValueRef,
  isGlobal: Uint8,
  desc: string,
): NewSymbolCommand {
  return {
    opcode: NEW_SYMBOL,
    resultSlot,
    isGlobal,
    desc,
  }
}

export function NewFloat64Cmd(resultSlot: JSValueRef, value: Float64): NewFloat64Command {
  return {
    opcode: NEW_FLOAT64,
    resultSlot,
    value,
  }
}

export function NewStringCmd(resultSlot: JSValueRef, str: string): NewStringCommand {
  return {
    opcode: NEW_STRING,
    resultSlot,
    str,
  }
}

export function NewBigintInt64Cmd(resultSlot: JSValueRef, value: Int64): NewBigintInt64Command {
  return {
    opcode: NEW_BIGINT_INT64,
    resultSlot,
    value,
  }
}

export function NewBigintStrCmd(resultSlot: JSValueRef, str: string): NewBigintStrCommand {
  return {
    opcode: NEW_BIGINT_STR,
    resultSlot,
    str,
  }
}

export function NewFuncCmd(
  resultSlot: JSValueRef,
  arity: Uint8,
  isConstructor: Uint8,
  name: string,
  hostRefId: HostRefId,
): NewFuncCommand {
  return {
    opcode: NEW_FUNC,
    resultSlot,
    arity,
    isConstructor,
    name,
    hostRefId,
  }
}

export function SetStrValueCmd(
  targetSlot: JSValueRef,
  valueSlot: JSValueRef,
  flags: SetPropFlags,
  key: string,
): SetStrValueCommand {
  return {
    opcode: SET_STR_VALUE,
    targetSlot,
    valueSlot,
    flags,
    key,
  }
}

export function SetStrNullCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  key: string,
): SetStrNullCommand {
  return {
    opcode: SET_STR_NULL,
    targetSlot,
    flags,
    key,
  }
}

export function SetStrUndefCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  key: string,
): SetStrUndefCommand {
  return {
    opcode: SET_STR_UNDEF,
    targetSlot,
    flags,
    key,
  }
}

export function SetStrBoolCmd(
  targetSlot: JSValueRef,
  boolVal: Uint8,
  flags: SetPropFlags,
  key: string,
): SetStrBoolCommand {
  return {
    opcode: SET_STR_BOOL,
    targetSlot,
    boolVal,
    flags,
    key,
  }
}

export function SetStrInt32Cmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  key: string,
  intVal: Int32,
): SetStrInt32Command {
  return {
    opcode: SET_STR_INT32,
    targetSlot,
    flags,
    key,
    intVal,
  }
}

export function SetStrF64Cmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  f64Val: Float64,
  key: string,
): SetStrF64Command {
  return {
    opcode: SET_STR_F64,
    targetSlot,
    flags,
    f64Val,
    key,
  }
}

export function SetStrBigintCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  i64Val: Int64,
  key: string,
): SetStrBigintCommand {
  return {
    opcode: SET_STR_BIGINT,
    targetSlot,
    flags,
    i64Val,
    key,
  }
}

export function SetStrStringCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  str: string,
  key: string,
): SetStrStringCommand {
  return {
    opcode: SET_STR_STRING,
    targetSlot,
    flags,
    str,
    key,
  }
}

export function SetIdxValueCmd(
  targetSlot: JSValueRef,
  valueSlot: JSValueRef,
  flags: SetPropFlags,
  index: Uint32,
): SetIdxValueCommand {
  return {
    opcode: SET_IDX_VALUE,
    targetSlot,
    valueSlot,
    flags,
    index,
  }
}

export function SetIdxNullCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  index: Uint32,
): SetIdxNullCommand {
  return {
    opcode: SET_IDX_NULL,
    targetSlot,
    flags,
    index,
  }
}

export function SetIdxUndefCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  index: Uint32,
): SetIdxUndefCommand {
  return {
    opcode: SET_IDX_UNDEF,
    targetSlot,
    flags,
    index,
  }
}

export function SetIdxBoolCmd(
  targetSlot: JSValueRef,
  boolVal: Uint8,
  flags: SetPropFlags,
  index: Uint32,
): SetIdxBoolCommand {
  return {
    opcode: SET_IDX_BOOL,
    targetSlot,
    boolVal,
    flags,
    index,
  }
}

export function SetIdxInt32Cmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  index: Uint32,
  intVal: Int32,
): SetIdxInt32Command {
  return {
    opcode: SET_IDX_INT32,
    targetSlot,
    flags,
    index,
    intVal,
  }
}

export function SetIdxF64Cmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  f64Val: Float64,
  index: Uint32,
): SetIdxF64Command {
  return {
    opcode: SET_IDX_F64,
    targetSlot,
    flags,
    f64Val,
    index,
  }
}

export function SetIdxBigintCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  i64Val: Int64,
  index: Uint32,
): SetIdxBigintCommand {
  return {
    opcode: SET_IDX_BIGINT,
    targetSlot,
    flags,
    i64Val,
    index,
  }
}

export function SetIdxStringCmd(
  targetSlot: JSValueRef,
  flags: SetPropFlags,
  str: string,
  index: Uint32,
): SetIdxStringCommand {
  return {
    opcode: SET_IDX_STRING,
    targetSlot,
    flags,
    str,
    index,
  }
}

export function SetValueValueCmd(
  targetSlot: JSValueRef,
  keySlot: JSValueRef,
  valueSlot: JSValueRef,
  flags: SetPropFlags,
): SetValueValueCommand {
  return {
    opcode: SET_VALUE_VALUE,
    targetSlot,
    keySlot,
    valueSlot,
    flags,
  }
}

export function DefValueGetsetCmd(
  targetSlot: JSValueRef,
  flags: JSPropFlags,
  getterRef: HostRefId,
  setterRef: HostRefId,
  key: string,
): DefValueGetsetCommand {
  return {
    opcode: DEF_VALUE_GETSET,
    targetSlot,
    flags,
    getterRef,
    setterRef,
    key,
  }
}

export function GetValueCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  keySlot: JSValueRef,
): GetValueCommand {
  return {
    opcode: GET_VALUE,
    resultSlot,
    sourceSlot,
    keySlot,
  }
}

export function GetStrCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  key: string,
): GetStrCommand {
  return {
    opcode: GET_STR,
    resultSlot,
    sourceSlot,
    key,
  }
}

export function GetIdxCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  index: Uint32,
): GetIdxCommand {
  return {
    opcode: GET_IDX,
    resultSlot,
    sourceSlot,
    index,
  }
}

export function GlobalCmd(resultSlot: JSValueRef): GlobalCommand {
  return {
    opcode: GLOBAL,
    resultSlot,
  }
}

export function GlobalGetStrCmd(resultSlot: JSValueRef, key: string): GlobalGetStrCommand {
  return {
    opcode: GLOBAL_GET_STR,
    resultSlot,
    key,
  }
}

export function GlobalSetStrCmd(
  valueSlot: JSValueRef,
  flags: JSPropFlags,
  key: string,
): GlobalSetStrCommand {
  return {
    opcode: GLOBAL_SET_STR,
    valueSlot,
    flags,
    key,
  }
}

export function MapSetCmd(
  targetSlot: JSValueRef,
  keySlot: JSValueRef,
  valueSlot: JSValueRef,
): MapSetCommand {
  return {
    opcode: MAP_SET,
    targetSlot,
    keySlot,
    valueSlot,
  }
}

export function MapSetStrCmd(
  targetSlot: JSValueRef,
  valueSlot: JSValueRef,
  key: string,
): MapSetStrCommand {
  return {
    opcode: MAP_SET_STR,
    targetSlot,
    valueSlot,
    key,
  }
}

export function SetAddCmd(targetSlot: JSValueRef, valueSlot: JSValueRef): SetAddCommand {
  return {
    opcode: SET_ADD,
    targetSlot,
    valueSlot,
  }
}

export function CallCmd(
  resultSlot: JSValueRef,
  funcSlot: JSValueRef,
  thisSlot: JSValueRef,
  argc: Uint8,
  arg1: JSValueRef,
  arg2: JSValueRef,
  arg3: JSValueRef,
  arg4: JSValueRef,
  arg5: JSValueRef,
  arg6: JSValueRef,
  arg7: JSValueRef,
  arg8: JSValueRef,
  arg9: JSValueRef,
  arg10: JSValueRef,
  callAsConstructor: Uint8,
): CallCommand {
  return {
    opcode: CALL,
    resultSlot,
    funcSlot,
    thisSlot,
    argc,
    arg1,
    arg2,
    arg3,
    arg4,
    arg5,
    arg6,
    arg7,
    arg8,
    arg9,
    arg10,
    callAsConstructor,
  }
}

export function CallArgvCmd(
  resultSlot: JSValueRef,
  funcSlot: JSValueRef,
  thisSlot: JSValueRef,
  argc: Uint32,
  argv: JSValuePointer,
  callAsConstructor: Uint32,
): CallArgvCommand {
  return {
    opcode: CALL_ARGV,
    resultSlot,
    funcSlot,
    thisSlot,
    argc,
    argv,
    callAsConstructor,
  }
}

export function EvalCmd(
  resultSlot: JSValueRef,
  callFlags: EvalFlags,
  code: string,
  filename: string,
): EvalCommand {
  return {
    opcode: EVAL,
    resultSlot,
    callFlags,
    code,
    filename,
  }
}

export function ThrowCmd(errorSlot: JSValueRef): ThrowCommand {
  return {
    opcode: THROW,
    errorSlot,
  }
}

export function ResolveExcCmd(resultSlot: JSValueRef, maybeExcSlot: JSValueRef): ResolveExcCommand {
  return {
    opcode: RESOLVE_EXC,
    resultSlot,
    maybeExcSlot,
  }
}

export function BytecodeWriteCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  flags: Uint32,
): BytecodeWriteCommand {
  return {
    opcode: BYTECODE_WRITE,
    resultSlot,
    sourceSlot,
    flags,
  }
}

export function BytecodeReadCmd(
  resultSlot: JSValueRef,
  sourceSlot: JSValueRef,
  flags: Uint32,
): BytecodeReadCommand {
  return {
    opcode: BYTECODE_READ,
    resultSlot,
    sourceSlot,
    flags,
  }
}

export function FunclistNewCmd(resultFunclistSlot: FuncListRef, count: Uint32): FunclistNewCommand {
  return {
    opcode: FUNCLIST_NEW,
    resultFunclistSlot,
    count,
  }
}

export function FunclistAssignCmd(
  targetSlot: JSValueRef,
  sourceFunclistSlot: FuncListRef,
): FunclistAssignCommand {
  return {
    opcode: FUNCLIST_ASSIGN,
    targetSlot,
    sourceFunclistSlot,
  }
}

export function FunclistDefCfuncCmd(
  targetFunclistSlot: FuncListRef,
  arity: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  funcName: string,
  cFuncPtr: JSCFunctionTypePointer,
): FunclistDefCfuncCommand {
  return {
    opcode: FUNCLIST_DEF_CFUNC,
    targetFunclistSlot,
    arity,
    flags,
    index,
    funcName,
    cFuncPtr,
  }
}

export function FunclistDefCfuncCtorCmd(
  targetFunclistSlot: FuncListRef,
  arity: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  funcName: string,
  cFuncPtr: JSCFunctionTypePointer,
): FunclistDefCfuncCtorCommand {
  return {
    opcode: FUNCLIST_DEF_CFUNC_CTOR,
    targetFunclistSlot,
    arity,
    flags,
    index,
    funcName,
    cFuncPtr,
  }
}

export function FunclistDefCgetsetCmd(
  targetFunclistSlot: FuncListRef,
  index: Uint8,
  flags: JSPropFlags,
  key: string,
  getterPtr: JSCFunctionTypePointer,
  setterPtr: JSCFunctionTypePointer,
): FunclistDefCgetsetCommand {
  return {
    opcode: FUNCLIST_DEF_CGETSET,
    targetFunclistSlot,
    index,
    flags,
    key,
    getterPtr,
    setterPtr,
  }
}

export function FunclistDefStringCmd(
  targetFunclistSlot: FuncListRef,
  index: Uint8,
  flags: JSPropFlags,
  str: string,
  name: string,
): FunclistDefStringCommand {
  return {
    opcode: FUNCLIST_DEF_STRING,
    targetFunclistSlot,
    index,
    flags,
    str,
    name,
  }
}

export function FunclistDefInt32Cmd(
  targetFunclistSlot: FuncListRef,
  flags: JSPropFlags,
  index: Uint32,
  intVal: Int32,
  key: string,
): FunclistDefInt32Command {
  return {
    opcode: FUNCLIST_DEF_INT32,
    targetFunclistSlot,
    flags,
    index,
    intVal,
    key,
  }
}

export function FunclistDefInt64Cmd(
  targetFunclistSlot: FuncListRef,
  index: Uint8,
  flags: JSPropFlags,
  i64Val: Int64,
  name: string,
): FunclistDefInt64Command {
  return {
    opcode: FUNCLIST_DEF_INT64,
    targetFunclistSlot,
    index,
    flags,
    i64Val,
    name,
  }
}

export function FunclistDefDoubleCmd(
  targetFunclistSlot: FuncListRef,
  index: Uint8,
  flags: JSPropFlags,
  f64Val: Float64,
  key: string,
): FunclistDefDoubleCommand {
  return {
    opcode: FUNCLIST_DEF_DOUBLE,
    targetFunclistSlot,
    index,
    flags,
    f64Val,
    key,
  }
}

export function FunclistDefNullCmd(
  targetFunclistSlot: FuncListRef,
  flags: JSPropFlags,
  key: string,
  index: Uint32,
): FunclistDefNullCommand {
  return {
    opcode: FUNCLIST_DEF_NULL,
    targetFunclistSlot,
    flags,
    key,
    index,
  }
}

export function FunclistDefUndefinedCmd(
  targetFunclistSlot: FuncListRef,
  flags: JSPropFlags,
  key: string,
  index: Uint32,
): FunclistDefUndefinedCommand {
  return {
    opcode: FUNCLIST_DEF_UNDEFINED,
    targetFunclistSlot,
    flags,
    key,
    index,
  }
}

export function FunclistDefObjectCmd(
  targetFunclistSlot: FuncListRef,
  objectFunclistSlot: FuncListRef,
  flags: JSPropFlags,
  key: string,
  index: Uint32,
): FunclistDefObjectCommand {
  return {
    opcode: FUNCLIST_DEF_OBJECT,
    targetFunclistSlot,
    objectFunclistSlot,
    flags,
    key,
    index,
  }
}

export function FunclistDefBoolCmd(
  targetFunclistSlot: FuncListRef,
  flags: JSPropFlags,
  index: Uint32,
  boolVal: Int32,
  key: string,
): FunclistDefBoolCommand {
  return {
    opcode: FUNCLIST_DEF_BOOL,
    targetFunclistSlot,
    flags,
    index,
    boolVal,
    key,
  }
}

export function forEachReadRef(command: Command, visit: RefVisitor): void {
  switch (command.opcode) {
    case SLOT_STORE:
      visit(command.inSlot)
      return
    case SLOT_FREE:
    case SET_STR_NULL:
    case SET_STR_UNDEF:
    case SET_STR_BOOL:
    case SET_STR_INT32:
    case SET_STR_F64:
    case SET_STR_BIGINT:
    case SET_STR_STRING:
    case SET_IDX_NULL:
    case SET_IDX_UNDEF:
    case SET_IDX_BOOL:
    case SET_IDX_INT32:
    case SET_IDX_F64:
    case SET_IDX_BIGINT:
    case SET_IDX_STRING:
    case DEF_VALUE_GETSET:
      visit(command.targetSlot)
      return
    case NEW_OBJECT_PROTO:
      visit(command.protoSlot)
      return
    case NEW_TYPED_ARRAY:
    case GET_STR:
    case GET_IDX:
    case BYTECODE_WRITE:
    case BYTECODE_READ:
      visit(command.sourceSlot)
      return
    case SET_STR_VALUE:
    case SET_IDX_VALUE:
    case MAP_SET_STR:
    case SET_ADD:
      visit(command.targetSlot)
      visit(command.valueSlot)
      return
    case SET_VALUE_VALUE:
    case MAP_SET:
      visit(command.targetSlot)
      visit(command.keySlot)
      visit(command.valueSlot)
      return
    case GET_VALUE:
      visit(command.sourceSlot)
      visit(command.keySlot)
      return
    case GLOBAL_SET_STR:
      visit(command.valueSlot)
      return
    case CALL:
      visit(command.funcSlot)
      visit(command.thisSlot)
      visit(command.arg1)
      visit(command.arg2)
      visit(command.arg3)
      visit(command.arg4)
      visit(command.arg5)
      visit(command.arg6)
      visit(command.arg7)
      visit(command.arg8)
      visit(command.arg9)
      visit(command.arg10)
      return
    case CALL_ARGV:
      visit(command.funcSlot)
      visit(command.thisSlot)
      return
    case THROW:
      visit(command.errorSlot)
      return
    case RESOLVE_EXC:
      visit(command.maybeExcSlot)
      return
    case FUNCLIST_ASSIGN:
      visit(command.targetSlot)
      visit(command.sourceFunclistSlot)
      return
    case FUNCLIST_DEF_CFUNC:
    case FUNCLIST_DEF_CFUNC_CTOR:
    case FUNCLIST_DEF_CGETSET:
    case FUNCLIST_DEF_STRING:
    case FUNCLIST_DEF_INT32:
    case FUNCLIST_DEF_INT64:
    case FUNCLIST_DEF_DOUBLE:
    case FUNCLIST_DEF_NULL:
    case FUNCLIST_DEF_UNDEFINED:
    case FUNCLIST_DEF_BOOL:
      visit(command.targetFunclistSlot)
      return
    case FUNCLIST_DEF_OBJECT:
      visit(command.targetFunclistSlot)
      visit(command.objectFunclistSlot)
      return
    default:
      return
  }
}

export function forEachWriteRef(command: Command, visit: RefVisitor): void {
  switch (command.opcode) {
    case SLOT_LOAD:
      visit(command.outSlot)
      return
    case NEW_OBJECT:
    case NEW_OBJECT_PROTO:
    case NEW_ARRAY:
    case NEW_MAP:
    case NEW_SET:
    case NEW_DATE:
    case NEW_ERROR:
    case NEW_ARRAYBUFFER:
    case NEW_TYPED_ARRAY:
    case NEW_SYMBOL:
    case NEW_FLOAT64:
    case NEW_STRING:
    case NEW_BIGINT_INT64:
    case NEW_BIGINT_STR:
    case NEW_FUNC:
    case GET_VALUE:
    case GET_STR:
    case GET_IDX:
    case GLOBAL:
    case GLOBAL_GET_STR:
    case CALL:
    case CALL_ARGV:
    case EVAL:
    case RESOLVE_EXC:
    case BYTECODE_WRITE:
    case BYTECODE_READ:
      visit(command.resultSlot)
      return
    case FUNCLIST_NEW:
      visit(command.resultFunclistSlot)
      return
    default:
      return
  }
}

export function forEachConsumedRef(command: Command, visit: RefVisitor): void {
  switch (command.opcode) {
    case SLOT_FREE:
      visit(command.targetSlot)
      return
    default:
      return
  }
}

function getCommandKind(command: { opcode: number }): number {
  return command.opcode
}

export function writeCommand(
  view: DataView,
  offset: CommandPtr,
  command: Command,
  helpers: CommandWriteHelpers,
): void {
  switch (command.opcode) {
    case INVALID: {
      return writeInvalid(view, offset)
    }
    case SLOT_STORE: {
      return writeSlotStore(
        view,
        offset,
        helpers.resolveRef(command.inSlot),
        command.inSlotType,
        command.outPtr,
      )
    }
    case SLOT_LOAD: {
      return writeSlotLoad(
        view,
        offset,
        helpers.resolveRef(command.outSlot),
        command.outSlotType,
        command.inPtr,
      )
    }
    case SLOT_FREE: {
      return writeSlotFree(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.targetSlotType,
      )
    }
    case NEW_OBJECT: {
      return writeNewObject(view, offset, helpers.resolveRef(command.resultSlot))
    }
    case NEW_OBJECT_PROTO: {
      return writeNewObjectProto(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.protoSlot),
      )
    }
    case NEW_ARRAY: {
      return writeNewArray(view, offset, helpers.resolveRef(command.resultSlot))
    }
    case NEW_MAP: {
      return writeNewMap(view, offset, helpers.resolveRef(command.resultSlot))
    }
    case NEW_SET: {
      return writeNewSet(view, offset, helpers.resolveRef(command.resultSlot))
    }
    case NEW_DATE: {
      return writeNewDate(view, offset, helpers.resolveRef(command.resultSlot), command.timestamp)
    }
    case NEW_ERROR: {
      const message = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(
        command.message,
        0xffffffff,
      )
      const name = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.name, 0xff, false)
      return writeNewError(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        name.len,
        command.newErrorFlags,
        message.ptr,
        message.len,
        name.ptr,
      )
    }
    case NEW_ARRAYBUFFER: {
      const dataBytes = helpers.encodeBytes<JSVoidPointer, Uint32>(command.dataBytes, 0xffffffff)
      return writeNewArraybuffer(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        command.classIsSharedArrayBuffer,
        dataBytes.ptr,
        dataBytes.len,
      )
    }
    case NEW_TYPED_ARRAY: {
      return writeNewTypedArray(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        command.arrayType,
        command.sourceOffset,
        command.length,
      )
    }
    case NEW_SYMBOL: {
      const desc = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.desc, 0xffffffff)
      return writeNewSymbol(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        command.isGlobal,
        desc.ptr,
        desc.len,
      )
    }
    case NEW_FLOAT64: {
      return writeNewFloat64(view, offset, helpers.resolveRef(command.resultSlot), command.value)
    }
    case NEW_STRING: {
      const str = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.str, 0xffffffff)
      return writeNewString(view, offset, helpers.resolveRef(command.resultSlot), str.ptr, str.len)
    }
    case NEW_BIGINT_INT64: {
      return writeNewBigintInt64(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        command.value,
      )
    }
    case NEW_BIGINT_STR: {
      const str = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.str, 0xffffffff)
      return writeNewBigintStr(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        str.ptr,
        str.len,
      )
    }
    case NEW_FUNC: {
      const name = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.name, 0xffffffff)
      return writeNewFunc(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        command.arity,
        command.isConstructor,
        name.ptr,
        name.len,
        command.hostRefId,
      )
    }
    case SET_STR_VALUE: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeSetStrValue(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.valueSlot),
        command.flags,
        key.ptr,
        key.len,
      )
    }
    case SET_STR_NULL: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeSetStrNull(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        key.ptr,
        key.len,
      )
    }
    case SET_STR_UNDEF: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeSetStrUndef(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        key.ptr,
        key.len,
      )
    }
    case SET_STR_BOOL: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeSetStrBool(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.boolVal,
        command.flags,
        key.ptr,
        key.len,
      )
    }
    case SET_STR_INT32: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeSetStrInt32(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        key.ptr,
        key.len,
        command.intVal,
      )
    }
    case SET_STR_F64: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeSetStrF64(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        key.len,
        command.flags,
        command.f64Val,
        key.ptr,
      )
    }
    case SET_STR_BIGINT: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeSetStrBigint(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        key.len,
        command.flags,
        command.i64Val,
        key.ptr,
      )
    }
    case SET_STR_STRING: {
      const str = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.str, 0xffffffff)
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeSetStrString(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        key.len,
        command.flags,
        str.ptr,
        str.len,
        key.ptr,
      )
    }
    case SET_IDX_VALUE: {
      return writeSetIdxValue(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.valueSlot),
        command.flags,
        command.index,
      )
    }
    case SET_IDX_NULL: {
      return writeSetIdxNull(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        command.index,
      )
    }
    case SET_IDX_UNDEF: {
      return writeSetIdxUndef(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        command.index,
      )
    }
    case SET_IDX_BOOL: {
      return writeSetIdxBool(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.boolVal,
        command.flags,
        command.index,
      )
    }
    case SET_IDX_INT32: {
      return writeSetIdxInt32(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        command.index,
        command.intVal,
      )
    }
    case SET_IDX_F64: {
      return writeSetIdxF64(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        command.f64Val,
        command.index,
      )
    }
    case SET_IDX_BIGINT: {
      return writeSetIdxBigint(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        command.i64Val,
        command.index,
      )
    }
    case SET_IDX_STRING: {
      const str = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.str, 0xffffffff)
      return writeSetIdxString(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        command.flags,
        str.ptr,
        str.len,
        command.index,
      )
    }
    case SET_VALUE_VALUE: {
      return writeSetValueValue(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.keySlot),
        helpers.resolveRef(command.valueSlot),
        command.flags,
      )
    }
    case DEF_VALUE_GETSET: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeDefValueGetset(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        key.len,
        command.flags,
        command.getterRef,
        command.setterRef,
        key.ptr,
      )
    }
    case GET_VALUE: {
      return writeGetValue(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        helpers.resolveRef(command.keySlot),
      )
    }
    case GET_STR: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeGetStr(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        key.ptr,
        key.len,
      )
    }
    case GET_IDX: {
      return writeGetIdx(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        command.index,
      )
    }
    case GLOBAL: {
      return writeGlobal(view, offset, helpers.resolveRef(command.resultSlot))
    }
    case GLOBAL_GET_STR: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeGlobalGetStr(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        key.ptr,
        key.len,
      )
    }
    case GLOBAL_SET_STR: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeGlobalSetStr(
        view,
        offset,
        helpers.resolveRef(command.valueSlot),
        command.flags,
        key.ptr,
        key.len,
      )
    }
    case MAP_SET: {
      return writeMapSet(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.keySlot),
        helpers.resolveRef(command.valueSlot),
      )
    }
    case MAP_SET_STR: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeMapSetStr(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.valueSlot),
        key.ptr,
        key.len,
      )
    }
    case SET_ADD: {
      return writeSetAdd(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.valueSlot),
      )
    }
    case CALL: {
      return writeCall(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.funcSlot),
        helpers.resolveRef(command.thisSlot),
        command.argc,
        helpers.resolveRef(command.arg1),
        helpers.resolveRef(command.arg2),
        helpers.resolveRef(command.arg3),
        helpers.resolveRef(command.arg4),
        helpers.resolveRef(command.arg5),
        helpers.resolveRef(command.arg6),
        helpers.resolveRef(command.arg7),
        helpers.resolveRef(command.arg8),
        helpers.resolveRef(command.arg9),
        helpers.resolveRef(command.arg10),
        command.callAsConstructor,
      )
    }
    case CALL_ARGV: {
      return writeCallArgv(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.funcSlot),
        helpers.resolveRef(command.thisSlot),
        command.argc,
        command.argv,
        command.callAsConstructor,
      )
    }
    case EVAL: {
      const code = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.code, 0xffffffff)
      const filename = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(
        command.filename,
        0xff,
        false,
      )
      return writeEval(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        filename.len,
        command.callFlags,
        code.ptr,
        code.len,
        filename.ptr,
      )
    }
    case THROW: {
      return writeThrow(view, offset, helpers.resolveRef(command.errorSlot))
    }
    case RESOLVE_EXC: {
      return writeResolveExc(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.maybeExcSlot),
      )
    }
    case BYTECODE_WRITE: {
      return writeBytecodeWrite(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        command.flags,
      )
    }
    case BYTECODE_READ: {
      return writeBytecodeRead(
        view,
        offset,
        helpers.resolveRef(command.resultSlot),
        helpers.resolveRef(command.sourceSlot),
        command.flags,
      )
    }
    case FUNCLIST_NEW: {
      return writeFunclistNew(
        view,
        offset,
        helpers.resolveRef(command.resultFunclistSlot),
        command.count,
      )
    }
    case FUNCLIST_ASSIGN: {
      return writeFunclistAssign(
        view,
        offset,
        helpers.resolveRef(command.targetSlot),
        helpers.resolveRef(command.sourceFunclistSlot),
      )
    }
    case FUNCLIST_DEF_CFUNC: {
      const funcName = helpers.encodeUtf8<BorrowedHeapCharPointer>(
        command.funcName,
        undefined,
        true,
      )
      return writeFunclistDefCfunc(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.arity,
        command.flags,
        command.index,
        funcName.ptr,
        command.cFuncPtr,
      )
    }
    case FUNCLIST_DEF_CFUNC_CTOR: {
      const funcName = helpers.encodeUtf8<BorrowedHeapCharPointer>(
        command.funcName,
        undefined,
        true,
      )
      return writeFunclistDefCfuncCtor(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.arity,
        command.flags,
        command.index,
        funcName.ptr,
        command.cFuncPtr,
      )
    }
    case FUNCLIST_DEF_CGETSET: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer>(command.key, undefined, true)
      return writeFunclistDefCgetset(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.index,
        command.flags,
        key.ptr,
        command.getterPtr,
        command.setterPtr,
      )
    }
    case FUNCLIST_DEF_STRING: {
      const str = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.str, 0xffffffff)
      const name = helpers.encodeUtf8<BorrowedHeapCharPointer>(command.name, undefined, true)
      return writeFunclistDefString(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.index,
        command.flags,
        str.ptr,
        str.len,
        name.ptr,
      )
    }
    case FUNCLIST_DEF_INT32: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeFunclistDefInt32(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        key.len,
        command.flags,
        command.index,
        command.intVal,
        key.ptr,
      )
    }
    case FUNCLIST_DEF_INT64: {
      const name = helpers.encodeUtf8<BorrowedHeapCharPointer>(command.name, undefined, true)
      return writeFunclistDefInt64(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.index,
        command.flags,
        command.i64Val,
        name.ptr,
      )
    }
    case FUNCLIST_DEF_DOUBLE: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer>(command.key, undefined, true)
      return writeFunclistDefDouble(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.index,
        command.flags,
        command.f64Val,
        key.ptr,
      )
    }
    case FUNCLIST_DEF_NULL: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeFunclistDefNull(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.flags,
        key.ptr,
        key.len,
        command.index,
      )
    }
    case FUNCLIST_DEF_UNDEFINED: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeFunclistDefUndefined(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        command.flags,
        key.ptr,
        key.len,
        command.index,
      )
    }
    case FUNCLIST_DEF_OBJECT: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint32>(command.key, 0xffffffff)
      return writeFunclistDefObject(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        helpers.resolveRef(command.objectFunclistSlot),
        command.flags,
        key.ptr,
        key.len,
        command.index,
      )
    }
    case FUNCLIST_DEF_BOOL: {
      const key = helpers.encodeUtf8<BorrowedHeapCharPointer, Uint8>(command.key, 0xff, false)
      return writeFunclistDefBool(
        view,
        offset,
        helpers.resolveRef(command.targetFunclistSlot),
        key.len,
        command.flags,
        command.index,
        command.boolVal,
        key.ptr,
      )
    }
    default:
      throw new Error(`Unknown command opcode: ${getCommandKind(command)}`)
  }
}

// =============================================================================

// Setter Helpers

// =============================================================================

function setOpcode(view: DataView, offset: number, opcode: number): void {
  view.setUint8(offset + 0, opcode)
}

function setSlotA(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 1, slot)
}

function setSlotB(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 2, slot)
}

function setSlotC(view: DataView, offset: number, slot: number): void {
  view.setUint8(offset + 3, slot)
}

function setD1_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 4, value, true)
}

function setD2_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 8, value, true)
}

function setD2_i32(view: DataView, offset: number, value: number): void {
  view.setInt32(offset + 8, value, true)
}

function setD3_u32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset + 12, value, true)
}

function setD3_i32(view: DataView, offset: number, value: number): void {
  view.setInt32(offset + 12, value, true)
}

function setData_f64(view: DataView, offset: number, value: number): void {
  view.setFloat64(offset + 4, value, true)
}

function setData_i64(view: DataView, offset: number, value: bigint): void {
  view.setBigInt64(offset + 4, value, true)
}

function writePattern0(
  view: DataView,
  offset: CommandPtr,
  p0: AnySlot,
  p1: SlotType,
  p2: JSVoidPointer,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setD1_u32(view, offset, p2)
}

function writePattern2(view: DataView, offset: CommandPtr, p0: JSValueSlot): void {
  setSlotA(view, offset, p0)
}

function writePattern3(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: JSValueSlot): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
}

function writePattern4(view: DataView, offset: CommandPtr, p0: JSValueSlot, p1: Float64): void {
  setSlotA(view, offset, p0)
  setData_f64(view, offset, p1)
}

function writePattern9(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: BorrowedHeapCharPointer,
  p2: Uint32,
): void {
  setSlotA(view, offset, p0)
  setD1_u32(view, offset, p1)
  setD2_u32(view, offset, p2)
}

function writePattern13(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: SetPropFlags,
  p2: BorrowedHeapCharPointer,
  p3: Uint32,
): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
}

function writePattern20(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: SetPropFlags,
  p2: Uint32,
): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
}

function writePattern28(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: JSValueSlot,
  p2: JSValueSlot,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setSlotC(view, offset, p2)
}

function writePattern29(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: JSValueSlot,
  p2: BorrowedHeapCharPointer,
  p3: Uint32,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
}

function writePattern30(
  view: DataView,
  offset: CommandPtr,
  p0: JSValueSlot,
  p1: JSValueSlot,
  p2: Uint32,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setD1_u32(view, offset, p2)
}

function writePattern37(
  view: DataView,
  offset: CommandPtr,
  p0: FuncListSlot,
  p1: Uint8,
  p2: JSPropFlags,
  p3: Uint32,
  p4: BorrowedHeapCharPointer,
  p5: JSCFunctionTypePointer,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setSlotC(view, offset, p2)
  setD1_u32(view, offset, p3)
  setD2_u32(view, offset, p4)
  setD3_u32(view, offset, p5)
}

function writePattern40(
  view: DataView,
  offset: CommandPtr,
  p0: FuncListSlot,
  p1: Uint8,
  p2: JSPropFlags,
  p3: Uint32,
  p4: Int32,
  p5: BorrowedHeapCharPointer,
): void {
  setSlotA(view, offset, p0)
  setSlotB(view, offset, p1)
  setSlotC(view, offset, p2)
  setD1_u32(view, offset, p3)
  setD2_i32(view, offset, p4)
  setD3_u32(view, offset, p5)
}

function writePattern43(
  view: DataView,
  offset: CommandPtr,
  p0: FuncListSlot,
  p1: JSPropFlags,
  p2: BorrowedHeapCharPointer,
  p3: Uint32,
  p4: Uint32,
): void {
  setSlotA(view, offset, p0)
  setSlotC(view, offset, p1)
  setD1_u32(view, offset, p2)
  setD2_u32(view, offset, p3)
  setD3_u32(view, offset, p4)
}

// =============================================================================

// Writer Functions (generated)

// =============================================================================

export function writeInvalid(view: DataView, offset: CommandPtr): void {
  setOpcode(view, offset, 0)
}

export function writeSlotStore(
  view: DataView,
  offset: CommandPtr,
  in_slot: AnySlot,
  in_slot_type: SlotType,
  out_ptr: JSVoidPointer,
): void {
  setOpcode(view, offset, 1)
  writePattern0(view, offset, in_slot, in_slot_type, out_ptr)
}

export function writeSlotLoad(
  view: DataView,
  offset: CommandPtr,
  out_slot: AnySlot,
  out_slot_type: SlotType,
  in_ptr: JSVoidPointer,
): void {
  setOpcode(view, offset, 2)
  writePattern0(view, offset, out_slot, out_slot_type, in_ptr)
}

export function writeSlotFree(
  view: DataView,
  offset: CommandPtr,
  target_slot: AnySlot,
  target_slot_type: SlotType,
): void {
  setOpcode(view, offset, 3)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, target_slot_type)
}

export function writeNewObject(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 4)
  writePattern2(view, offset, result_slot)
}

export function writeNewObjectProto(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  proto_slot: JSValueSlot,
): void {
  setOpcode(view, offset, 5)
  writePattern3(view, offset, result_slot, proto_slot)
}

export function writeNewArray(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 6)
  writePattern2(view, offset, result_slot)
}

export function writeNewMap(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 7)
  writePattern2(view, offset, result_slot)
}

export function writeNewSet(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 8)
  writePattern2(view, offset, result_slot)
}

export function writeNewDate(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  timestamp: Float64,
): void {
  setOpcode(view, offset, 9)
  writePattern4(view, offset, result_slot, timestamp)
}

export function writeNewError(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  maybe_name_len: Uint8,
  new_error_flags: NewErrorFlags,
  message_ptr: BorrowedHeapCharPointer,
  message_len: Uint32,
  name_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 10)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, maybe_name_len)
  setSlotC(view, offset, new_error_flags)
  setD1_u32(view, offset, message_ptr)
  setD2_u32(view, offset, message_len)
  setD3_u32(view, offset, name_ptr)
}

export function writeNewArraybuffer(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  class_is_shared_array_buffer: Uint8,
  data_ptr: JSVoidPointer,
  data_len: Uint32,
): void {
  setOpcode(view, offset, 11)
  setSlotA(view, offset, result_slot)
  setSlotC(view, offset, class_is_shared_array_buffer)
  setD1_u32(view, offset, data_ptr)
  setD2_u32(view, offset, data_len)
}

export function writeNewTypedArray(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  array_type: NewTypedArrayFlags,
  source_offset: Uint32,
  length: Uint32,
): void {
  setOpcode(view, offset, 12)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, source_slot)
  setSlotC(view, offset, array_type)
  setD1_u32(view, offset, source_offset)
  setD2_u32(view, offset, length)
}

export function writeNewSymbol(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  is_global: Uint8,
  desc_ptr: BorrowedHeapCharPointer,
  desc_len: Uint32,
): void {
  setOpcode(view, offset, 13)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, is_global)
  setD1_u32(view, offset, desc_ptr)
  setD2_u32(view, offset, desc_len)
}

export function writeNewFloat64(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  value: Float64,
): void {
  setOpcode(view, offset, 14)
  writePattern4(view, offset, result_slot, value)
}

export function writeNewString(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  str_ptr: BorrowedHeapCharPointer,
  str_len: Uint32,
): void {
  setOpcode(view, offset, 15)
  writePattern9(view, offset, result_slot, str_ptr, str_len)
}

export function writeNewBigintInt64(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  value: Int64,
): void {
  setOpcode(view, offset, 16)
  setSlotA(view, offset, result_slot)
  setData_i64(view, offset, value)
}

export function writeNewBigintStr(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  str_ptr: BorrowedHeapCharPointer,
  str_len: Uint32,
): void {
  setOpcode(view, offset, 17)
  writePattern9(view, offset, result_slot, str_ptr, str_len)
}

export function writeNewFunc(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  arity: Uint8,
  is_constructor: Uint8,
  name_ptr: BorrowedHeapCharPointer,
  name_len: Uint32,
  host_ref_id: HostRefId,
): void {
  setOpcode(view, offset, 18)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, arity)
  setSlotC(view, offset, is_constructor)
  setD1_u32(view, offset, name_ptr)
  setD2_u32(view, offset, name_len)
  setD3_u32(view, offset, host_ref_id)
}

export function writeSetStrValue(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  value_slot: JSValueSlot,
  flags: SetPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 19)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeSetStrNull(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 20)
  writePattern13(view, offset, target_slot, flags, key_ptr, key_len)
}

export function writeSetStrUndef(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 21)
  writePattern13(view, offset, target_slot, flags, key_ptr, key_len)
}

export function writeSetStrBool(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  bool_val: Uint8,
  flags: SetPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 22)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, bool_val)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeSetStrInt32(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
  int_val: Int32,
): void {
  setOpcode(view, offset, 23)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
  setD3_i32(view, offset, int_val)
}

export function writeSetStrF64(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  maybe_key_len: Uint8,
  flags: SetPropFlags,
  f64_val: Float64,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 24)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetStrBigint(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  maybe_key_len: Uint8,
  flags: SetPropFlags,
  i64_val: Int64,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 25)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetStrString(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  maybe_key_len: Uint8,
  flags: SetPropFlags,
  str_ptr: BorrowedHeapCharPointer,
  str_len: Uint32,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 26)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, key_ptr)
}

export function writeSetIdxValue(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  value_slot: JSValueSlot,
  flags: SetPropFlags,
  index: Uint32,
): void {
  setOpcode(view, offset, 27)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
}

export function writeSetIdxNull(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  index: Uint32,
): void {
  setOpcode(view, offset, 28)
  writePattern20(view, offset, target_slot, flags, index)
}

export function writeSetIdxUndef(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  index: Uint32,
): void {
  setOpcode(view, offset, 29)
  writePattern20(view, offset, target_slot, flags, index)
}

export function writeSetIdxBool(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  bool_val: Uint8,
  flags: SetPropFlags,
  index: Uint32,
): void {
  setOpcode(view, offset, 30)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, bool_val)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
}

export function writeSetIdxInt32(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  index: Uint32,
  int_val: Int32,
): void {
  setOpcode(view, offset, 31)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, index)
  setD2_i32(view, offset, int_val)
}

export function writeSetIdxF64(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  f64_val: Float64,
  index: Uint32,
): void {
  setOpcode(view, offset, 32)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, index)
}

export function writeSetIdxBigint(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  i64_val: Int64,
  index: Uint32,
): void {
  setOpcode(view, offset, 33)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, index)
}

export function writeSetIdxString(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  flags: SetPropFlags,
  str_ptr: BorrowedHeapCharPointer,
  str_len: Uint32,
  index: Uint32,
): void {
  setOpcode(view, offset, 34)
  setSlotA(view, offset, target_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, index)
}

export function writeSetValueValue(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  key_slot: JSValueSlot,
  value_slot: JSValueSlot,
  flags: SetPropFlags,
): void {
  setOpcode(view, offset, 35)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, key_slot)
  setSlotC(view, offset, value_slot)
  setD1_u32(view, offset, flags)
}

export function writeDefValueGetset(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  maybe_key_len: Uint8,
  flags: JSPropFlags,
  getter_ref: HostRefId,
  setter_ref: HostRefId,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 36)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, maybe_key_len)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, getter_ref)
  setD2_u32(view, offset, setter_ref)
  setD3_u32(view, offset, key_ptr)
}

export function writeGetValue(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  key_slot: JSValueSlot,
): void {
  setOpcode(view, offset, 37)
  writePattern28(view, offset, result_slot, source_slot, key_slot)
}

export function writeGetStr(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 38)
  writePattern29(view, offset, result_slot, source_slot, key_ptr, key_len)
}

export function writeGetIdx(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  index: Uint32,
): void {
  setOpcode(view, offset, 39)
  writePattern30(view, offset, result_slot, source_slot, index)
}

export function writeGlobal(view: DataView, offset: CommandPtr, result_slot: JSValueSlot): void {
  setOpcode(view, offset, 40)
  writePattern2(view, offset, result_slot)
}

export function writeGlobalGetStr(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 41)
  writePattern9(view, offset, result_slot, key_ptr, key_len)
}

export function writeGlobalSetStr(
  view: DataView,
  offset: CommandPtr,
  value_slot: JSValueSlot,
  flags: JSPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 42)
  setSlotA(view, offset, value_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
}

export function writeMapSet(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  key_slot: JSValueSlot,
  value_slot: JSValueSlot,
): void {
  setOpcode(view, offset, 43)
  writePattern28(view, offset, target_slot, key_slot, value_slot)
}

export function writeMapSetStr(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  value_slot: JSValueSlot,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
): void {
  setOpcode(view, offset, 44)
  writePattern29(view, offset, target_slot, value_slot, key_ptr, key_len)
}

export function writeSetAdd(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  value_slot: JSValueSlot,
): void {
  setOpcode(view, offset, 45)
  writePattern3(view, offset, target_slot, value_slot)
}

export function writeCall(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  func_slot: JSValueSlot,
  this_slot: JSValueSlot,
  argc: Uint8,
  arg1: JSValueSlot,
  arg2: JSValueSlot,
  arg3: JSValueSlot,
  arg4: JSValueSlot,
  arg5: JSValueSlot,
  arg6: JSValueSlot,
  arg7: JSValueSlot,
  arg8: JSValueSlot,
  arg9: JSValueSlot,
  arg10: JSValueSlot,
  call_as_constructor: Uint8,
): void {
  setOpcode(view, offset, 46)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, func_slot)
  setSlotC(view, offset, this_slot)
  setD1_u32(
    view,
    offset,
    ((argc as number) & 0xff) |
      ((arg1 as number) & (0xff << 8)) |
      ((arg2 as number) & (0xff << 16)) |
      ((arg3 as number) & (0xff << 24)),
  )
  setD2_u32(
    view,
    offset,
    ((arg4 as number) & 0xff) |
      ((arg5 as number) & (0xff << 8)) |
      ((arg6 as number) & (0xff << 16)) |
      ((arg7 as number) & (0xff << 24)),
  )
  setD3_u32(
    view,
    offset,
    ((arg8 as number) & 0xff) |
      ((arg9 as number) & (0xff << 8)) |
      ((arg10 as number) & (0xff << 16)) |
      ((call_as_constructor as number) & (0xff << 24)),
  )
}

export function writeCallArgv(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  func_slot: JSValueSlot,
  this_slot: JSValueSlot,
  argc: Uint32,
  argv: JSValuePointer,
  call_as_constructor: Uint32,
): void {
  setOpcode(view, offset, 47)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, func_slot)
  setSlotC(view, offset, this_slot)
  setD1_u32(view, offset, argc)
  setD2_u32(view, offset, argv)
  setD3_u32(view, offset, call_as_constructor)
}

export function writeEval(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  maybe_filename_len: Uint8,
  call_flags: EvalFlags,
  code_ptr: BorrowedHeapCharPointer,
  code_len: Uint32,
  filename: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 48)
  setSlotA(view, offset, result_slot)
  setSlotB(view, offset, maybe_filename_len)
  setSlotC(view, offset, call_flags)
  setD1_u32(view, offset, code_ptr)
  setD2_u32(view, offset, code_len)
  setD3_u32(view, offset, filename)
}

export function writeThrow(view: DataView, offset: CommandPtr, error_slot: JSValueSlot): void {
  setOpcode(view, offset, 49)
  writePattern2(view, offset, error_slot)
}

export function writeResolveExc(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  maybe_exc_slot: JSValueSlot,
): void {
  setOpcode(view, offset, 50)
  writePattern3(view, offset, result_slot, maybe_exc_slot)
}

export function writeBytecodeWrite(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  flags: Uint32,
): void {
  setOpcode(view, offset, 51)
  writePattern30(view, offset, result_slot, source_slot, flags)
}

export function writeBytecodeRead(
  view: DataView,
  offset: CommandPtr,
  result_slot: JSValueSlot,
  source_slot: JSValueSlot,
  flags: Uint32,
): void {
  setOpcode(view, offset, 52)
  writePattern30(view, offset, result_slot, source_slot, flags)
}

export function writeFunclistNew(
  view: DataView,
  offset: CommandPtr,
  result_funclist_slot: FuncListSlot,
  count: Uint32,
): void {
  setOpcode(view, offset, 53)
  setSlotA(view, offset, result_funclist_slot)
  setD1_u32(view, offset, count)
}

export function writeFunclistAssign(
  view: DataView,
  offset: CommandPtr,
  target_slot: JSValueSlot,
  source_funclist_slot: FuncListSlot,
): void {
  setOpcode(view, offset, 54)
  setSlotA(view, offset, target_slot)
  setSlotB(view, offset, source_funclist_slot)
}

export function writeFunclistDefCfunc(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  arity: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  func_name_ptr: BorrowedHeapCharPointer,
  c_func_ptr: JSCFunctionTypePointer,
): void {
  setOpcode(view, offset, 55)
  writePattern37(view, offset, target_funclist_slot, arity, flags, index, func_name_ptr, c_func_ptr)
}

export function writeFunclistDefCfuncCtor(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  arity: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  func_name_ptr: BorrowedHeapCharPointer,
  c_func_ptr: JSCFunctionTypePointer,
): void {
  setOpcode(view, offset, 56)
  writePattern37(view, offset, target_funclist_slot, arity, flags, index, func_name_ptr, c_func_ptr)
}

export function writeFunclistDefCgetset(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  index: Uint8,
  flags: JSPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  getter_ptr: JSCFunctionTypePointer,
  setter_ptr: JSCFunctionTypePointer,
): void {
  setOpcode(view, offset, 57)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, getter_ptr)
  setD3_u32(view, offset, setter_ptr)
}

export function writeFunclistDefString(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  index: Uint8,
  flags: JSPropFlags,
  str_ptr: BorrowedHeapCharPointer,
  str_len: Uint32,
  name_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 58)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, str_ptr)
  setD2_u32(view, offset, str_len)
  setD3_u32(view, offset, name_ptr)
}

export function writeFunclistDefInt32(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  maybe_key_len: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  int_val: Int32,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 59)
  writePattern40(view, offset, target_funclist_slot, maybe_key_len, flags, index, int_val, key_ptr)
}

export function writeFunclistDefInt64(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  index: Uint8,
  flags: JSPropFlags,
  i64_val: Int64,
  name_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 60)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setData_i64(view, offset, i64_val)
  setD3_u32(view, offset, name_ptr)
}

export function writeFunclistDefDouble(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  index: Uint8,
  flags: JSPropFlags,
  f64_val: Float64,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 61)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, index)
  setSlotC(view, offset, flags)
  setData_f64(view, offset, f64_val)
  setD3_u32(view, offset, key_ptr)
}

export function writeFunclistDefNull(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  flags: JSPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
  index: Uint32,
): void {
  setOpcode(view, offset, 62)
  writePattern43(view, offset, target_funclist_slot, flags, key_ptr, key_len, index)
}

export function writeFunclistDefUndefined(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  flags: JSPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
  index: Uint32,
): void {
  setOpcode(view, offset, 63)
  writePattern43(view, offset, target_funclist_slot, flags, key_ptr, key_len, index)
}

export function writeFunclistDefObject(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  object_funclist_slot: FuncListSlot,
  flags: JSPropFlags,
  key_ptr: BorrowedHeapCharPointer,
  key_len: Uint32,
  index: Uint32,
): void {
  setOpcode(view, offset, 64)
  setSlotA(view, offset, target_funclist_slot)
  setSlotB(view, offset, object_funclist_slot)
  setSlotC(view, offset, flags)
  setD1_u32(view, offset, key_ptr)
  setD2_u32(view, offset, key_len)
  setD3_u32(view, offset, index)
}

export function writeFunclistDefBool(
  view: DataView,
  offset: CommandPtr,
  target_funclist_slot: FuncListSlot,
  maybe_key_len: Uint8,
  flags: JSPropFlags,
  index: Uint32,
  bool_val: Int32,
  key_ptr: BorrowedHeapCharPointer,
): void {
  setOpcode(view, offset, 65)
  writePattern40(view, offset, target_funclist_slot, maybe_key_len, flags, index, bool_val, key_ptr)
}

export const OP_ENCODERS = [
  writeInvalid,
  writeSlotStore,
  writeSlotLoad,
  writeSlotFree,
  writeNewObject,
  writeNewObjectProto,
  writeNewArray,
  writeNewMap,
  writeNewSet,
  writeNewDate,
  writeNewError,
  writeNewArraybuffer,
  writeNewTypedArray,
  writeNewSymbol,
  writeNewFloat64,
  writeNewString,
  writeNewBigintInt64,
  writeNewBigintStr,
  writeNewFunc,
  writeSetStrValue,
  writeSetStrNull,
  writeSetStrUndef,
  writeSetStrBool,
  writeSetStrInt32,
  writeSetStrF64,
  writeSetStrBigint,
  writeSetStrString,
  writeSetIdxValue,
  writeSetIdxNull,
  writeSetIdxUndef,
  writeSetIdxBool,
  writeSetIdxInt32,
  writeSetIdxF64,
  writeSetIdxBigint,
  writeSetIdxString,
  writeSetValueValue,
  writeDefValueGetset,
  writeGetValue,
  writeGetStr,
  writeGetIdx,
  writeGlobal,
  writeGlobalGetStr,
  writeGlobalSetStr,
  writeMapSet,
  writeMapSetStr,
  writeSetAdd,
  writeCall,
  writeCallArgv,
  writeEval,
  writeThrow,
  writeResolveExc,
  writeBytecodeWrite,
  writeBytecodeRead,
  writeFunclistNew,
  writeFunclistAssign,
  writeFunclistDefCfunc,
  writeFunclistDefCfuncCtor,
  writeFunclistDefCgetset,
  writeFunclistDefString,
  writeFunclistDefInt32,
  writeFunclistDefInt64,
  writeFunclistDefDouble,
  writeFunclistDefNull,
  writeFunclistDefUndefined,
  writeFunclistDefObject,
  writeFunclistDefBool,
] as const
